### ISSUE TITLE
Installation error using Rails 5.2.0.beta1

### ISSUE THREAD

**Issue by pbmarcano** [thoughtbot/administrate#1035]
Hi folks,

I know Rails 5.2 is in beta and not supported, but I tried anyways and ran into an error trying to install administrate.

Not sure if this is because of my use of the fairly new ActiveStorage framework, or if administrate is looking to call upon some ActiveRecord method that has gone missing.

Either way, I don't know how to fix it myself so thought I'd try to put it on someone's radar!

Thanks,
Pete

**Setup**
```ruby
# Gemfile
gem 'administrate', '~> 0.8.1' # also tried with github: 'thoughtbot/administrate'
```
```bash
# rails console
rails g install:administrate
```

**Output**
```bash
Running via Spring preloader in process 51002
       route  namespace :admin do
    resources :users
    resources :applications
    resources :application_references
    resources :batches
    resources :references
    resources :reference_types

    root to: "users#index"
  end
WARNING: Unable to generate a dashboard for ActiveStorage::Blob.
         Administrate does not yet support namespaced models.
      create  app/controllers/admin/application_controller.rb
      create  app/dashboards/user_dashboard.rb
      create  app/controllers/admin/users_controller.rb
/Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/activerecord-5.2.0.beta1/lib/active_record/reflection.rb:786:in `source_reflection': undefined method `klass' for nil:NilClass (NoMethodError)
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/activerecord-5.2.0.beta1/lib/active_record/reflection.rb:991:in `derive_class_name'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/activerecord-5.2.0.beta1/lib/active_record/reflection.rb:161:in `class_name'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/bundler/gems/administrate-2bc89d638937/lib/generators/administrate/dashboard/dashboard_generator.rb:121:in `relationship_options_string'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/bundler/gems/administrate-2bc89d638937/lib/generators/administrate/dashboard/dashboard_generator.rb:108:in `association_type'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/bundler/gems/administrate-2bc89d638937/lib/generators/administrate/dashboard/dashboard_generator.rb:67:in `redundant_attributes_for'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/bundler/gems/administrate-2bc89d638937/lib/generators/administrate/dashboard/dashboard_generator.rb:62:in `block in redundant_attributes'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/bundler/gems/administrate-2bc89d638937/lib/generators/administrate/dashboard/dashboard_generator.rb:61:in `each'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/bundler/gems/administrate-2bc89d638937/lib/generators/administrate/dashboard/dashboard_generator.rb:61:in `flat_map'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/bundler/gems/administrate-2bc89d638937/lib/generators/administrate/dashboard/dashboard_generator.rb:61:in `redundant_attributes'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/bundler/gems/administrate-2bc89d638937/lib/generators/administrate/dashboard/dashboard_generator.rb:53:in `attributes'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/bundler/gems/administrate-2bc89d638937/lib/generators/administrate/dashboard/templates/dashboard.rb.erb:11:in `template'
	from /Users/pbmarcano/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/erb.rb:896:in `eval'
	from /Users/pbmarcano/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/erb.rb:896:in `result'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/thor-0.20.0/lib/thor/actions/file_manipulation.rb:122:in `block in template'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/thor-0.20.0/lib/thor/actions/create_file.rb:53:in `render'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/thor-0.20.0/lib/thor/actions/create_file.rb:63:in `block (2 levels) in invoke!'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/thor-0.20.0/lib/thor/actions/create_file.rb:63:in `open'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/thor-0.20.0/lib/thor/actions/create_file.rb:63:in `block in invoke!'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/thor-0.20.0/lib/thor/actions/empty_directory.rb:117:in `invoke_with_conflict_check'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/thor-0.20.0/lib/thor/actions/create_file.rb:60:in `invoke!'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/thor-0.20.0/lib/thor/actions.rb:94:in `action'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/thor-0.20.0/lib/thor/actions/create_file.rb:25:in `create_file'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/thor-0.20.0/lib/thor/actions/file_manipulation.rb:119:in `template'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/railties-5.2.0.beta1/lib/rails/generators/named_base.rb:25:in `block in template'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/railties-5.2.0.beta1/lib/rails/generators/named_base.rb:49:in `inside_template'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/railties-5.2.0.beta1/lib/rails/generators/named_base.rb:24:in `template'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/bundler/gems/administrate-2bc89d638937/lib/generators/administrate/dashboard/dashboard_generator.rb:32:in `create_dashboard_definition'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `each'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `map'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `invoke_all'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/thor-0.20.0/lib/thor/group.rb:232:in `dispatch'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/railties-5.2.0.beta1/lib/rails/generators.rb:273:in `invoke'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/bundler/gems/administrate-2bc89d638937/lib/administrate/generator_helpers.rb:4:in `call_generator'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/bundler/gems/administrate-2bc89d638937/lib/generators/administrate/install/install_generator.rb:29:in `block in run_dashboard_generators'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/bundler/gems/administrate-2bc89d638937/lib/generators/administrate/install/install_generator.rb:28:in `each'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/bundler/gems/administrate-2bc89d638937/lib/generators/administrate/install/install_generator.rb:28:in `run_dashboard_generators'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `each'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `map'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `invoke_all'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/thor-0.20.0/lib/thor/group.rb:232:in `dispatch'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/railties-5.2.0.beta1/lib/rails/generators.rb:273:in `invoke'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/railties-5.2.0.beta1/lib/rails/commands/generate/generate_command.rb:26:in `perform'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/railties-5.2.0.beta1/lib/rails/command/base.rb:65:in `perform'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/railties-5.2.0.beta1/lib/rails/command.rb:46:in `invoke'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/railties-5.2.0.beta1/lib/rails/commands.rb:18:in `<top (required)>'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/activesupport-5.2.0.beta1/lib/active_support/dependencies.rb:283:in `require'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/activesupport-5.2.0.beta1/lib/active_support/dependencies.rb:283:in `block in require'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/activesupport-5.2.0.beta1/lib/active_support/dependencies.rb:249:in `load_dependency'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/activesupport-5.2.0.beta1/lib/active_support/dependencies.rb:283:in `require'
	from /Users/pbmarcano/Developer/simple_apply/bin/rails:9:in `<top (required)>'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/activesupport-5.2.0.beta1/lib/active_support/dependencies.rb:277:in `load'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/activesupport-5.2.0.beta1/lib/active_support/dependencies.rb:277:in `block in load'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/activesupport-5.2.0.beta1/lib/active_support/dependencies.rb:249:in `load_dependency'
	from /Users/pbmarcano/.rvm/gems/ruby-2.4.0/gems/activesupport-5.2.0.beta1/lib/active_support/dependencies.rb:277:in `load'
	from /Users/pbmarcano/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/pbmarcano/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

**Comment by nickcharlton** [comment]
Hi @pbmarcano!

Thanks for opening this. I always expect a few issues when new Rails versions come out and it's great to have someone try it out so fast.

I just created a sample app using `5.2.0.beta2` to try and replicate this, but it seems to install and setup fine.

Would you be able to share a sample of what you were seeing?

**Comment by pbmarcano** [comment]
Hi @nickcharlton,

As far as I know I just set up a simple crud app and tried to install administrate as I have done before and mentioned above.

Is it too much to ask to fork my relatively new app [pbmarcano/simple_apply](https://github.com/pbmarcano/simple_apply) and see if you can recreate it using my code?

Nothing really fancy in terms of setup., just clone and db:setup (with postgres), should get you going.

Using my best educated guess I think it's either ActiveStorage or something to do with my weird database structure having a rich join reference another rich join?

**Comment by nickcharlton** [comment]
Thanks for providing the same app! It's much easier when I can look at it properly.

I cloned and had a look, first at the error itself to see what administrate was doing (when building dashboards, it reflects on the attributes and relationships of the model) and then at the structure of your models. I think that's where the error is really coming from.

In [lib/generators/administrate/dashboard/dashboard_generator.rb:121](https://github.com/thoughtbot/administrate/blob/2bc89d6389377bd2e8b56b366e0041c307266195/lib/generators/administrate/dashboard/dashboard_generator.rb#L121), the class of the relationship for `references` on `Application` is nil. I think there are potentially two reasons for this, looking at [app/models/application.rb](https://github.com/pbmarcano/simple_apply/blob/11aaa107180cb0ad62d705853c9f59f39d6e9805/app/models/application.rb):

First, [`has_many :references, through: :applications` either isn't valid or is redundant as `applications` would be itself](http://guides.rubyonrails.org/association_basics.html#the-has-many-through-association). I wonder if your intention here is actually: `has_many :references, through: :application_references`?

Second, `references` is already a method of [`ActiveRecord::QueryMethods`](http://api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-references) and that'll be included in your `Application` class so that's possibly explaining some odd behaviour.

Does this help at all?

**Comment by pbmarcano** [comment]
@nickcharlton,

Oh man! **Thank you** so much for debugging my non-administrate problems! You definitely went above and beyond.

Send me a message on the best way I can buy you a pint from over the Atlantic as a token of my gratitude.

Made those two changes and the dashboard seems to run fine. Now I just have to make a new administrate-field to handle ActiveStorage file objects.

Wish me luck!

- Pete

**Comment by nickcharlton** [comment]
No worries! I'm glad I was able to help you. Providing the example app allows me to do that easily enough and it helps refresh my knowledge of Rails internals often, too!

I'd like to start having an up to date list of plugins, so please open a PR to add that to the docs if you're able to!
