### ISSUE TITLE
 Could not load generator "generators/administrate/routes/routes_generator". Error: Circular dependency detected while autoloading constant Administrate::ApplicationController.

### ISSUE THREAD

**Issue by amyin** [thoughtbot/administrate#1036]
I'm referencing 2bc89d6389377bd2e8b56b366e0041c307266195 in my Gemfile (latest commit from Nov 24th)

I have a model called "Admin" so I opted for a custom namespace Administrate. However when I run `rails generate administrate:install --namespace administrate` I get a circular dependency and some issues with routes generation

```
[WARNING] Could not load generator "generators/administrate/routes/routes_generator". Error: Circular dependency detected while autoloading constant Administrate::ApplicationController.
/Users/amyyin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:508:in `load_missing_constant'
/Users/amyyin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:202:in `const_missing'
/Users/amyyin/coinbase/weipay/api/app/controllers/administrate/application_controller.rb:8:in `<module:Administrate>'
/Users/amyyin/coinbase/weipay/api/app/controllers/administrate/application_controller.rb:7:in `<top (required)>'
/Users/amyyin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:476:in `load'
/Users/amyyin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:476:in `block in load_file'
/Users/amyyin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:661:in `new_constants_in'
/Users/amyyin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:475:in `load_file'
/Users/amyyin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:374:in `block in require_or_load'
/Users/amyyin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:36:in `block in load_interlock'
/Users/amyyin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
/Users/amyyin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/concurrency/share_lock.rb:149:in `exclusive'
/Users/amyyin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:11:in `loading'
/Users/amyyin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:36:in `load_interlock'
/Users/amyyin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:357:in `require_or_load'
/Users/amyyin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:335:in `depend_on'
/Users/amyyin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:251:in `require_dependency'
/Users/amyyin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/engine.rb:476:in `block (2 levels) in eager_load!'
/Users/amyyin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/engine.rb:475:in `each'
/Users/amyyin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/engine.rb:475:in `block in eager_load!'
/Users/amyyin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/engine.rb:473:in `each'
/Users/amyyin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/engine.rb:473:in `eager_load!'
/Users/amyyin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/bundler/gems/administrate-2bc89d638937/lib/generators/administrate/routes/routes_generator.rb:1:in `<top (required)>'
/Users/amyyin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
/Users/amyyin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
/Users/amyyin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
/Users/amyyin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
/Users/amyyin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/command/behavior.rb:82:in `block (2 levels) in lookup'
/Users/amyyin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/command/behavior.rb:78:in `each'
/Users/amyyin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/command/behavior.rb:78:in `block in lookup'
/Users/amyyin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/command/behavior.rb:77:in `each'
/Users/amyyin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/command/behavior.rb:77:in `lookup'
/Users/amyyin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/generators.rb:250:in `find_by_namespace'
/Users/amyyin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/generators.rb:267:in `invoke'
/Users/amyyin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/bundler/gems/administrate-2bc89d638937/lib/administrate/generator_helpers.rb:4:in `call_generator'
/Users/amyyin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/bundler/gems/administrate-2bc89d638937/lib/generators/administrate/install/install_generator.rb:15:in `run_routes_generator'
/Users/amyyin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
/Users/amyyin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
/Users/amyyin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `block in invoke_all'
/Users/amyyin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `each'
/Users/amyyin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `map'
/Users/amyyin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `invoke_all'
/Users/amyyin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/group.rb:232:in `dispatch'
/Users/amyyin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
/Users/amyyin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/generators.rb:269:in `invoke'
/Users/amyyin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/commands/generate/generate_command.rb:24:in `perform'
/Users/amyyin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
/Users/amyyin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
/Users/amyyin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
/Users/amyyin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/command/base.rb:63:in `perform'
/Users/amyyin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/command.rb:44:in `invoke'
/Users/amyyin/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<top (required)>'
bin/rails:9:in `require'
bin/rails:9:in `<main>'
Expected boolean default value for '--markerb'; got :erb (string)
Could not find generator 'administrate:routes'. Maybe you meant 'administrate:assets', 'administrate:views' or 'administrate:view'
Run `rails generate --help` for more options.
```

Any thoughts? Thanks in advance!

**Comment by amyin** [comment]
Never mind, I changed the namespace to admins and it was fine. `Administrate::ApplicationController` collides with the custom namespace of Administrate.

**Comment by nickcharlton** [comment]
Hi @amyin!

Thank you for opening this issue back then and I'm glad you figured out your problem in the end.

I'm going to (hopefully briefly!) reopen this to ask: Is it worth us expanding on our `--namespace` feature, or providing better error handling to avoid this in the future? Would you have any ideas on how that might be done?

**Comment by amyin** [comment]
I do think it's worthwhile changing since Admin is a common model name. I ended up using the namespace `control` because I didn't want to fight the generators. You could allow `admins` by adding another flag to not strip pluralization. The best solution though would be fixing the collision of the Admin model with the default namespace imo

**Comment by nickcharlton** [comment]
I'm going to close this as I'm not sure of a better solution than we have — we're working on the docs so this would be good to flag up there.
