### ISSUE TITLE
errors on create when `FORM_ATTRIBUTES = []`

### ISSUE THREAD

**Issue by ptolemybarnes** [thoughtbot/administrate#1093]
I have a dashboard where I've set:

```
FORM_ATTRIBUTES = [].freeze
```

.. as I don't want admins to provide any attributes for the resource on creation or update.

On submitting, I get:

```
ActionController::ParameterMissing in Admin::ResourceNameController#create

actionpack (5.1.4) lib/action_controller/metal/strong_parameters.rb:437:in `require'
administrate (0.8.1) app/controllers/administrate/application_controller.rb:122:in `resource_params'
administrate (0.8.1) app/controllers/administrate/application_controller.rb:42:in `create'
```

I guess because it's doing this:

```
ActionController::Parameters.new(resource_name: {}).require(:resource_name)
# => ActionController::ParameterMissing: param is missing or the value is empty: resource_name
```

Would you accept a PR that handles this case?

**Comment by nickcharlton** [comment]
A PR would be wonderful!

**Comment by pablobm** [comment]
Closing due to lack of activity 😞 Let us know if this should be reopened!
