### ISSUE TITLE
Could not find generator

### ISSUE THREAD

**Issue by michaelminter** [thoughtbot/administrate#1162]
Running `rails generate administrate:install --namespace manager`:

```
[WARNING] Could not load generator "generators/administrate/routes/routes_generator". Error: Admin is not a module.
/home/michael/RubymineProjects/NoowPT/app/controllers/admin/application_controller.rb:7:in `<top (required)>'
/home/michael/.rvm/gems/ruby-2.3.6@keet-core/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:457:in `load'
/home/michael/.rvm/gems/ruby-2.3.6@keet-core/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:457:in `block in load_file'
/home/michael/.rvm/gems/ruby-2.3.6@keet-core/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:647:in `new_constants_in'
/home/michael/.rvm/gems/ruby-2.3.6@keet-core/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:456:in `load_file'
/home/michael/.rvm/gems/ruby-2.3.6@keet-core/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:354:in `require_or_load'
/home/michael/.rvm/gems/ruby-2.3.6@keet-core/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:317:in `depend_on'
/home/michael/.rvm/gems/ruby-2.3.6@keet-core/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:233:in `require_dependency'
/home/michael/.rvm/gems/ruby-2.3.6@keet-core/gems/railties-4.2.10/lib/rails/engine.rb:472:in `block (2 levels) in eager_load!'
/home/michael/.rvm/gems/ruby-2.3.6@keet-core/gems/railties-4.2.10/lib/rails/engine.rb:471:in `each'
/home/michael/.rvm/gems/ruby-2.3.6@keet-core/gems/railties-4.2.10/lib/rails/engine.rb:471:in `block in eager_load!'
/home/michael/.rvm/gems/ruby-2.3.6@keet-core/gems/railties-4.2.10/lib/rails/engine.rb:469:in `each'
/home/michael/.rvm/gems/ruby-2.3.6@keet-core/gems/railties-4.2.10/lib/rails/engine.rb:469:in `eager_load!'
/home/michael/.rvm/gems/ruby-2.3.6@keet-core/gems/administrate-0.10.0/lib/generators/administrate/routes/routes_generator.rb:1:in `<top (required)>'
/home/michael/.rvm/gems/ruby-2.3.6@keet-core/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
/home/michael/.rvm/gems/ruby-2.3.6@keet-core/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
/home/michael/.rvm/gems/ruby-2.3.6@keet-core/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/michael/.rvm/gems/ruby-2.3.6@keet-core/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
/home/michael/.rvm/gems/ruby-2.3.6@keet-core/gems/railties-4.2.10/lib/rails/generators.rb:332:in `block (2 levels) in lookup'
/home/michael/.rvm/gems/ruby-2.3.6@keet-core/gems/railties-4.2.10/lib/rails/generators.rb:328:in `each'
/home/michael/.rvm/gems/ruby-2.3.6@keet-core/gems/railties-4.2.10/lib/rails/generators.rb:328:in `block in lookup'
/home/michael/.rvm/gems/ruby-2.3.6@keet-core/gems/railties-4.2.10/lib/rails/generators.rb:327:in `each'
/home/michael/.rvm/gems/ruby-2.3.6@keet-core/gems/railties-4.2.10/lib/rails/generators.rb:327:in `lookup'
/home/michael/.rvm/gems/ruby-2.3.6@keet-core/gems/railties-4.2.10/lib/rails/generators.rb:138:in `find_by_namespace'
/home/michael/.rvm/gems/ruby-2.3.6@keet-core/gems/railties-4.2.10/lib/rails/generators.rb:155:in `invoke'
/home/michael/.rvm/gems/ruby-2.3.6@keet-core/gems/administrate-0.10.0/lib/administrate/generator_helpers.rb:4:in `call_generator'
/home/michael/.rvm/gems/ruby-2.3.6@keet-core/gems/administrate-0.10.0/lib/generators/administrate/install/install_generator.rb:15:in `run_routes_generator'
/home/michael/.rvm/gems/ruby-2.3.6@keet-core/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
/home/michael/.rvm/gems/ruby-2.3.6@keet-core/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
/home/michael/.rvm/gems/ruby-2.3.6@keet-core/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `block in invoke_all'
/home/michael/.rvm/gems/ruby-2.3.6@keet-core/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `each'
/home/michael/.rvm/gems/ruby-2.3.6@keet-core/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `map'
/home/michael/.rvm/gems/ruby-2.3.6@keet-core/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `invoke_all'
/home/michael/.rvm/gems/ruby-2.3.6@keet-core/gems/thor-0.20.0/lib/thor/group.rb:232:in `dispatch'
/home/michael/.rvm/gems/ruby-2.3.6@keet-core/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
/home/michael/.rvm/gems/ruby-2.3.6@keet-core/gems/railties-4.2.10/lib/rails/generators.rb:157:in `invoke'
/home/michael/.rvm/gems/ruby-2.3.6@keet-core/gems/railties-4.2.10/lib/rails/commands/generate.rb:13:in `<top (required)>'
/home/michael/.rvm/gems/ruby-2.3.6@keet-core/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
/home/michael/.rvm/gems/ruby-2.3.6@keet-core/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
/home/michael/.rvm/gems/ruby-2.3.6@keet-core/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/michael/.rvm/gems/ruby-2.3.6@keet-core/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
/home/michael/.rvm/gems/ruby-2.3.6@keet-core/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
/home/michael/.rvm/gems/ruby-2.3.6@keet-core/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:130:in `generate_or_destroy'
/home/michael/.rvm/gems/ruby-2.3.6@keet-core/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:50:in `generate'
/home/michael/.rvm/gems/ruby-2.3.6@keet-core/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
/home/michael/.rvm/gems/ruby-2.3.6@keet-core/gems/railties-4.2.10/lib/rails/commands.rb:17:in `<top (required)>'
/home/michael/.rvm/gems/ruby-2.3.6@keet-core/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
/home/michael/.rvm/gems/ruby-2.3.6@keet-core/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
/home/michael/.rvm/gems/ruby-2.3.6@keet-core/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/michael/.rvm/gems/ruby-2.3.6@keet-core/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
/home/michael/RubymineProjects/NoowPT/bin/rails:9:in `<top (required)>'
/home/michael/.rvm/gems/ruby-2.3.6@keet-core/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
/home/michael/.rvm/gems/ruby-2.3.6@keet-core/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `block in load'
/home/michael/.rvm/gems/ruby-2.3.6@keet-core/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/michael/.rvm/gems/ruby-2.3.6@keet-core/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
/home/michael/.rvm/rubies/ruby-2.3.6/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/michael/.rvm/rubies/ruby-2.3.6/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
-e:1:in `<main>'
Could not find generator 'administrate:routes'. Maybe you meant 'administrate:assets', 'administrate:view' or 'administrate:views'
Run `rails generate --help` for more options.
```

**Comment by nvonpentz** [comment]
+1

**Comment by JIAZHEN** [comment]
Have you tried to strop spring? `spring stop`

**Comment by pablobm** [comment]
As the last two commenters proposed, I think it's either Spring or a class/module definition mismatch. Closing. Please let us know if you see this problem again.
