### ISSUE TITLE
Could not load generator "generators/administrate/routes/routes_generator". Error: uninitialized constant Administrate::BaseDashboard

### ISSUE THREAD

**Issue by krainboltgreene** [thoughtbot/administrate#1221]
- ruby-2.5.0
  - administrate-0.11.0

```
[WARNING] Could not load generator "generators/administrate/routes/routes_generator". Error: uninitialized constant Administrate::BaseDashboard.
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:53:in `block in load_missing_constant'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:8:in `without_bootsnap_cache'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:53:in `rescue in load_missing_constant'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:42:in `load_missing_constant'
/Users/krainboltgreene/Code/krainboltgreene/thebountycall/app/dashboards/application_dashboard.rb:1:in `<main>'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:100:in `load'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:100:in `load'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.1/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies/interlock.rb:13:in `loading'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:43:in `load_missing_constant'
/Users/krainboltgreene/Code/krainboltgreene/thebountycall/app/dashboards/account_dashboard.rb:1:in `<main>'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:100:in `load'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:100:in `load'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.1/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies/interlock.rb:13:in `loading'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:59:in `depend_on'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/railties-5.2.1/lib/rails/engine.rb:478:in `block (2 levels) in eager_load!'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/railties-5.2.1/lib/rails/engine.rb:477:in `each'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/railties-5.2.1/lib/rails/engine.rb:477:in `block in eager_load!'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/railties-5.2.1/lib/rails/engine.rb:475:in `each'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/railties-5.2.1/lib/rails/engine.rb:475:in `eager_load!'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/administrate-0.11.0/lib/generators/administrate/routes/routes_generator.rb:1:in `<main>'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/railties-5.2.1/lib/rails/command/behavior.rb:84:in `block (2 levels) in lookup'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/railties-5.2.1/lib/rails/command/behavior.rb:80:in `each'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/railties-5.2.1/lib/rails/command/behavior.rb:80:in `block in lookup'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/railties-5.2.1/lib/rails/command/behavior.rb:79:in `each'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/railties-5.2.1/lib/rails/command/behavior.rb:79:in `lookup'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/railties-5.2.1/lib/rails/generators.rb:257:in `find_by_namespace'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/railties-5.2.1/lib/rails/generators.rb:274:in `invoke'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/administrate-0.11.0/lib/administrate/generator_helpers.rb:4:in `call_generator'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/administrate-0.11.0/lib/generators/administrate/install/install_generator.rb:15:in `run_routes_generator'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `block in invoke_all'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `each'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `map'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `invoke_all'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/thor-0.20.0/lib/thor/group.rb:232:in `dispatch'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/railties-5.2.1/lib/rails/generators.rb:276:in `invoke'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/railties-5.2.1/lib/rails/commands/generate/generate_command.rb:26:in `perform'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/railties-5.2.1/lib/rails/command/base.rb:65:in `perform'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/railties-5.2.1/lib/rails/command.rb:46:in `invoke'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/railties-5.2.1/lib/rails/commands.rb:18:in `<main>'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
bin/rails:4:in `<main>'
Could not find generator 'administrate:routes'. Maybe you meant 'administrate:assets', 'administrate:view' or 'administrate:views'
```

**Comment by krainboltgreene** [comment]
Turns out I didn't have `require "administrate/base_dashboard"`.
