### ISSUE TITLE
ActionView::Template::Error (The asset is not present in the asset pipeline.)

### ISSUE THREAD

**Issue by hegwin** [thoughtbot/administrate#1302]
## Enviroments

Ruby 2.5.3
Rails 5.2.2.1
Administrate 0.11.0

## Description

I have added a custom CSS file `app/assets/stylesheets/administrate/main.scss`

In `initializers/assets.rb`, I added
```ruby
Administrate::Engine.add_stylesheet('administrate/main')
```

And in `initializers/administrate.rb` I had
```ruby
Rails.application.config.assets.precompile += %w( administrate/main.css )
```

It works in development, but when I deploy my app to staging, I get an error:
```
F, [2019-03-21T08:42:47.919553 #8] FATAL -- : [037969dd-3a1e-4867-94bd-22eeff070636]
F, [2019-03-21T08:42:47.919595 #8] FATAL -- : [037969dd-3a1e-4867-94bd-22eeff070636] ActionView::Template::Error (The asset “administrate/main.css" is not present in the asset pipeline.):
F, [2019-03-21T08:42:47.919700 #8] FATAL -- : [037969dd-3a1e-4867-94bd-22eeff070636]      8: %>
[037969dd-3a1e-4867-94bd-22eeff070636]      9:
[037969dd-3a1e-4867-94bd-22eeff070636]     10: <% Administrate::Engine.stylesheets.each do |css_path| %>
[037969dd-3a1e-4867-94bd-22eeff070636]     11:   <%= stylesheet_link_tag css_path %>
[037969dd-3a1e-4867-94bd-22eeff070636]     12: <% end %>
[037969dd-3a1e-4867-94bd-22eeff070636]     13:
[037969dd-3a1e-4867-94bd-22eeff070636]     14: <%= yield :stylesheet %>
F, [2019-03-21T08:42:47.919724 #8] FATAL -- : [037969dd-3a1e-4867-94bd-22eeff070636]
F, [2019-03-21T08:42:47.919793 #8] FATAL -- : [037969dd-3a1e-4867-94bd-22eeff070636] sprockets-rails (3.2.1) lib/sprockets/rails/helper.rb:83:in `compute_asset_path'
[037969dd-3a1e-4867-94bd-22eeff070636] actionview (5.2.2.1) lib/action_view/helpers/asset_url_helper.rb:200:in `asset_path'
[037969dd-3a1e-4867-94bd-22eeff070636] actionview (5.2.2.1) lib/action_view/helpers/asset_url_helper.rb:345:in `stylesheet_path'
```

Btw, I also tried `rails generate administrate:assets:stylesheets`, but I met the issue in #429 and can’t resolve it.

**Comment by purinkle** [comment]
@hegwin, is this still an issue for you?

**Comment by hegwin** [comment]
I fixed it by adding these two lines to my Dockerfile for building app images:

```
RUN SECRET_KEY_BASE="Hello, Assets!" RAILS_ENV=production bundle exec rake assets:precompile
RUN SECRET_KEY_BASE="I'm bored with you!" RAILS_ENV=staging bundle exec rake assets:precompile
```

I’m not sure if it is a correct way to resolve it..

**Comment by purinkle** [comment]
@nickcharlton, do you think this could be a case of an undocumented `rake assets:precompile` stage?
