### ISSUE TITLE
uninitialized constant Analytics (NameError)

### ISSUE THREAD

**Issue by kshtzkr** [thoughtbot/administrate#1541]
Unable to generate the dashboard and controller
`rails g administrate:dashboard Analytics`
`  - Rails(4.2.10)
  - administrate(0.10.0)`

````
create  app/dashboards/analytics_dashboard.rb
Traceback (most recent call last):
	36: from bin/rails:9:in `<main>'
	35: from bin/rails:9:in `require'
	34: from /home/kshitiz/kshitiz/GoTasker/vendor/cache/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands.rb:17:in `<top (required)>'
	33: from /home/kshitiz/kshitiz/GoTasker/vendor/cache/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	32: from /home/kshitiz/kshitiz/GoTasker/vendor/cache/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:50:in `generate'
	31: from /home/kshitiz/kshitiz/GoTasker/vendor/cache/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:130:in `generate_or_destroy'
	30: from /home/kshitiz/kshitiz/GoTasker/vendor/cache/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
	29: from /home/kshitiz/kshitiz/GoTasker/vendor/cache/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/generate.rb:13:in `<top (required)>'
	28: from /home/kshitiz/kshitiz/GoTasker/vendor/cache/ruby/2.5.0/gems/railties-4.2.10/lib/rails/generators.rb:157:in `invoke'
	27: from /home/kshitiz/kshitiz/GoTasker/vendor/cache/ruby/2.5.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	26: from /home/kshitiz/kshitiz/GoTasker/vendor/cache/ruby/2.5.0/gems/thor-0.19.4/lib/thor/group.rb:232:in `dispatch'
	25: from /home/kshitiz/kshitiz/GoTasker/vendor/cache/ruby/2.5.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `invoke_all'
	24: from /home/kshitiz/kshitiz/GoTasker/vendor/cache/ruby/2.5.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `map'
	23: from /home/kshitiz/kshitiz/GoTasker/vendor/cache/ruby/2.5.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `each'
	22: from /home/kshitiz/kshitiz/GoTasker/vendor/cache/ruby/2.5.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `block in invoke_all'
	21: from /home/kshitiz/kshitiz/GoTasker/vendor/cache/ruby/2.5.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	20: from /home/kshitiz/kshitiz/GoTasker/vendor/cache/ruby/2.5.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	19: from /home/kshitiz/kshitiz/GoTasker/vendor/cache/ruby/2.5.0/gems/administrate-0.10.0/lib/generators/administrate/dashboard/dashboard_generator.rb:32:in `create_dashboard_definition'
	18: from /home/kshitiz/kshitiz/GoTasker/vendor/cache/ruby/2.5.0/gems/railties-4.2.10/lib/rails/generators/named_base.rb:25:in `template'
	17: from /home/kshitiz/kshitiz/GoTasker/vendor/cache/ruby/2.5.0/gems/railties-4.2.10/lib/rails/generators/named_base.rb:60:in `inside_template'
	16: from /home/kshitiz/kshitiz/GoTasker/vendor/cache/ruby/2.5.0/gems/railties-4.2.10/lib/rails/generators/named_base.rb:26:in `block in template'
	15: from /home/kshitiz/kshitiz/GoTasker/vendor/cache/ruby/2.5.0/gems/thor-0.19.4/lib/thor/actions/file_manipulation.rb:115:in `template'
	14: from /home/kshitiz/kshitiz/GoTasker/vendor/cache/ruby/2.5.0/gems/thor-0.19.4/lib/thor/actions/create_file.rb:25:in `create_file'
	13: from /home/kshitiz/kshitiz/GoTasker/vendor/cache/ruby/2.5.0/gems/thor-0.19.4/lib/thor/actions.rb:95:in `action'
	12: from /home/kshitiz/kshitiz/GoTasker/vendor/cache/ruby/2.5.0/gems/thor-0.19.4/lib/thor/actions/create_file.rb:60:in `invoke!'
	11: from /home/kshitiz/kshitiz/GoTasker/vendor/cache/ruby/2.5.0/gems/thor-0.19.4/lib/thor/actions/empty_directory.rb:116:in `invoke_with_conflict_check'
	10: from /home/kshitiz/kshitiz/GoTasker/vendor/cache/ruby/2.5.0/gems/thor-0.19.4/lib/thor/actions/create_file.rb:62:in `block in invoke!'
	 9: from /home/kshitiz/kshitiz/GoTasker/vendor/cache/ruby/2.5.0/gems/thor-0.19.4/lib/thor/actions/create_file.rb:62:in `open'
	 8: from /home/kshitiz/kshitiz/GoTasker/vendor/cache/ruby/2.5.0/gems/thor-0.19.4/lib/thor/actions/create_file.rb:62:in `block (2 levels) in invoke!'
	 7: from /home/kshitiz/kshitiz/GoTasker/vendor/cache/ruby/2.5.0/gems/thor-0.19.4/lib/thor/actions/create_file.rb:53:in `render'
	 6: from /home/kshitiz/kshitiz/GoTasker/vendor/cache/ruby/2.5.0/gems/thor-0.19.4/lib/thor/actions/file_manipulation.rb:116:in `block in template'
	 5: from /home/kshitiz/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/erb.rb:876:in `result'
	 4: from /home/kshitiz/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/erb.rb:876:in `eval'
	 3: from (erb):11:in `template'
	 2: from /home/kshitiz/kshitiz/GoTasker/vendor/cache/ruby/2.5.0/gems/administrate-0.10.0/lib/generators/administrate/dashboard/dashboard_generator.rb:53:in `attributes'
	 1: from /home/kshitiz/kshitiz/GoTasker/vendor/cache/ruby/2.5.0/gems/administrate-0.10.0/lib/generators/administrate/dashboard/dashboard_generator.rb:117:in `klass'
/home/kshitiz/kshitiz/GoTasker/vendor/cache/ruby/2.5.0/gems/administrate-0.10.0/lib/generators/administrate/dashboard/dashboard_generator.rb:117:in `const_get': uninitialized constant Analytics (NameError)
```
`

**Comment by b4thestorm** [comment]
hey @kshtzkr are you certain that you have a db table and class with a name matching Analytics? 

If you do, try `rails g administrate:dashboard Analytic`

**Comment by nickcharlton** [comment]
I'm going to close this because there's been no activity since the end of January. This is a common problem, which would be nice to be able to catch and warn nicely (if any one wanted to pick that up).
