### ISSUE TITLE
undefined method `class_name' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by dheeraj2dj** [thoughtbot/administrate#1628]
* What were you trying to do?
  - I have a Rails API-only Application - created with `rails new my_api --api`
  - I have added `administrate` to this app & was trying to install it with `rails generate administrate:install`, which is when the following error occured
  - I have some models with this kind of association - `has_many :comments, class_name: 'PostComment'`

* What did you end up with (logs, or, even better, example apps are great!)?
```
Traceback (most recent call last):
	63: from bin/rails:4:in `<main>'
	62: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `require'
	61: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:291:in `load_dependency'
	60: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `block in require'
	59: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	58: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	57: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	56: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	55: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	54: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/railties-6.0.2.1/lib/rails/commands.rb:18:in `<main>'
	53: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/railties-6.0.2.1/lib/rails/command.rb:46:in `invoke'
	52: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/railties-6.0.2.1/lib/rails/command/base.rb:69:in `perform'
	51: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	50: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	49: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	48: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/railties-6.0.2.1/lib/rails/commands/generate/generate_command.rb:26:in `perform'
	47: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/railties-6.0.2.1/lib/rails/generators.rb:276:in `invoke'
	46: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	45: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/thor-1.0.1/lib/thor/group.rb:232:in `dispatch'
	44: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `invoke_all'
	43: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `map'
	42: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `each'
	41: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `block in invoke_all'
	40: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	39: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	38: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/administrate-0.13.0/lib/generators/administrate/install/install_generator.rb:28:in `run_dashboard_generators'
	37: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/administrate-0.13.0/lib/generators/administrate/install/install_generator.rb:28:in `each'
	36: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/administrate-0.13.0/lib/generators/administrate/install/install_generator.rb:29:in `block in run_dashboard_generators'
	35: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/administrate-0.13.0/lib/administrate/generator_helpers.rb:4:in `call_generator'
	34: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/railties-6.0.2.1/lib/rails/generators.rb:276:in `invoke'
	33: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	32: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/thor-1.0.1/lib/thor/group.rb:232:in `dispatch'
	31: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `invoke_all'
	30: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `map'
	29: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `each'
	28: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `block in invoke_all'
	27: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	26: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	25: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/administrate-0.13.0/lib/generators/administrate/dashboard/dashboard_generator.rb:32:in `create_dashboard_definition'
	24: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/railties-6.0.2.1/lib/rails/generators/named_base.rb:24:in `template'
	23: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/railties-6.0.2.1/lib/rails/generators/named_base.rb:45:in `inside_template'
	22: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/railties-6.0.2.1/lib/rails/generators/named_base.rb:25:in `block in template'
	21: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/thor-1.0.1/lib/thor/actions/file_manipulation.rb:122:in `template'
	20: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/thor-1.0.1/lib/thor/actions/create_file.rb:25:in `create_file'
	19: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/thor-1.0.1/lib/thor/actions.rb:93:in `action'
	18: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/thor-1.0.1/lib/thor/actions/create_file.rb:60:in `invoke!'
	17: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/thor-1.0.1/lib/thor/actions/empty_directory.rb:115:in `invoke_with_conflict_check'
	16: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/thor-1.0.1/lib/thor/actions/create_file.rb:73:in `on_conflict_behavior'
	15: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/thor-1.0.1/lib/thor/actions/create_file.rb:46:in `identical?'
	14: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/thor-1.0.1/lib/thor/actions/create_file.rb:53:in `render'
	13: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/thor-1.0.1/lib/thor/actions/file_manipulation.rb:131:in `block in template'
	12: from /Users/dheeraj2dj/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/erb.rb:901:in `result'
	11: from /Users/dheeraj2dj/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/erb.rb:901:in `eval'
	10: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/administrate-0.13.0/lib/generators/administrate/dashboard/templates/dashboard.rb.erb:11:in `template'
	 9: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/administrate-0.13.0/lib/generators/administrate/dashboard/dashboard_generator.rb:55:in `attributes'
	 8: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/administrate-0.13.0/lib/generators/administrate/dashboard/dashboard_generator.rb:63:in `redundant_attributes'
	 7: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/administrate-0.13.0/lib/generators/administrate/dashboard/dashboard_generator.rb:63:in `flat_map'
	 6: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/administrate-0.13.0/lib/generators/administrate/dashboard/dashboard_generator.rb:63:in `each'
	 5: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/administrate-0.13.0/lib/generators/administrate/dashboard/dashboard_generator.rb:64:in `block in redundant_attributes'
	 4: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/administrate-0.13.0/lib/generators/administrate/dashboard/dashboard_generator.rb:69:in `redundant_attributes_for'
	 3: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/administrate-0.13.0/lib/generators/administrate/dashboard/dashboard_generator.rb:110:in `association_type'
	 2: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/administrate-0.13.0/lib/generators/administrate/dashboard/dashboard_generator.rb:123:in `relationship_options_string'
	 1: from /Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.2.1/lib/active_record/reflection.rb:166:in `class_name'
/Users/dheeraj2dj/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.2.1/lib/active_record/reflection.rb:989:in `derive_class_name': undefined method `class_name' for nil:NilClass (NoMethodError)
Did you mean?  class_eval
```

* What versions are you running?
  - Ruby -> `2.6.3`
  - Rails -> `6.0.2.1`
  - administrate -> `0.13.0`

**Comment by nickcharlton** [comment]
Can you show what the association code looks like? Is there the correct `belongs_to` on the other side?

**Comment by dheeraj2dj** [comment]
Associations

<img width="421" alt="Screenshot 2020-05-07 at 12 38 21 AM" src="https://user-images.githubusercontent.com/2561485/81217974-1465ca80-8ffb-11ea-8be2-394cab863a4c.png">
<img width="374" alt="Screenshot 2020-05-07 at 12 35 50 AM" src="https://user-images.githubusercontent.com/2561485/81217897-f730fc00-8ffa-11ea-90ba-4251ffcf5827.png">

**Comment by pablobm** [comment]
I've tried to reproduce this, but I failed. I'm not sure that the `class_name` option is the problem here; it might be a red herring. Is there anything else that could be out of the ordinary?

**Comment by nickcharlton** [comment]
I'm going to close this as it's been a inactive for a while, please re-open if you're still struggling with it.
