### ISSUE TITLE
Install fails if ActiveAdmin is already present in the project

### ISSUE THREAD

**Issue by mshappe** [thoughtbot/administrate#1647]
* What were you trying to do?

`rails g adminstrate:install`

* What did you end up with (logs, or, even better, example apps are great!)?

```
Traceback (most recent call last):
        68: from -e:1:in `<main>'
        67: from /root/.rbenv/versions/2.6.6/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        66: from /root/.rbenv/versions/2.6.6/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        65: from /app/vendor/bundle/ruby/2.6.0/gems/spring-2.1.0/lib/spring/application/boot.rb:19:in `<top (required)>'
        64: from /app/vendor/bundle/ruby/2.6.0/gems/spring-2.1.0/lib/spring/application.rb:139:in `run'
        63: from /app/vendor/bundle/ruby/2.6.0/gems/spring-2.1.0/lib/spring/application.rb:139:in `loop'
        62: from /app/vendor/bundle/ruby/2.6.0/gems/spring-2.1.0/lib/spring/application.rb:145:in `block in run'
        61: from /app/vendor/bundle/ruby/2.6.0/gems/spring-2.1.0/lib/spring/application.rb:175:in `serve'
        60: from /app/vendor/bundle/ruby/2.6.0/gems/spring-2.1.0/lib/spring/application.rb:175:in `fork'
        59: from /app/vendor/bundle/ruby/2.6.0/gems/spring-2.1.0/lib/spring/application.rb:215:in `block in serve'
        58: from /app/vendor/bundle/ruby/2.6.0/gems/spring-2.1.0/lib/spring/command_wrapper.rb:38:in `call'
        57: from /app/vendor/bundle/ruby/2.6.0/gems/spring-2.1.0/lib/spring/commands/rails.rb:6:in `call'
        56: from /app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
        55: from /app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
        54: from /app/bin/rails:15:in `<main>'
        53: from /app/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.3.0/lib/zeitwerk/kernel.rb:23:in `require'
        52: from /app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        51: from /app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        50: from /app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        49: from /app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        48: from /app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        47: from /app/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2.2/lib/rails/commands.rb:18:in `<main>'
        46: from /app/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2.2/lib/rails/command.rb:46:in `invoke'
        45: from /app/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2.2/lib/rails/command/base.rb:69:in `perform'
        44: from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        43: from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        42: from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        41: from /app/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2.2/lib/rails/commands/generate/generate_command.rb:26:in `perform'
        40: from /app/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2.2/lib/rails/generators.rb:276:in `invoke'
        39: from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        38: from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/group.rb:232:in `dispatch'
        37: from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `invoke_all'
        36: from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `map'
        35: from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `each'
        34: from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `block in invoke_all'
        33: from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        32: from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        31: from /app/vendor/bundle/ruby/2.6.0/gems/administrate-0.13.0/lib/generators/administrate/install/install_generator.rb:28:in `run_dashboard_generators'
        30: from /app/vendor/bundle/ruby/2.6.0/gems/administrate-0.13.0/lib/generators/administrate/install/install_generator.rb:28:in `each'
        29: from /app/vendor/bundle/ruby/2.6.0/gems/administrate-0.13.0/lib/generators/administrate/install/install_generator.rb:29:in `block in run_dashboard_generators'
        28: from /app/vendor/bundle/ruby/2.6.0/gems/administrate-0.13.0/lib/administrate/generator_helpers.rb:4:in `call_generator'
        27: from /app/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2.2/lib/rails/generators.rb:276:in `invoke'
        26: from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        25: from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/group.rb:232:in `dispatch'
        24: from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `invoke_all'
        23: from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `map'
        22: from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `each'
        21: from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `block in invoke_all'
        20: from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        19: from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        18: from /app/vendor/bundle/ruby/2.6.0/gems/administrate-0.13.0/lib/generators/administrate/dashboard/dashboard_generator.rb:32:in `create_dashboard_definition'
        17: from /app/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2.2/lib/rails/generators/named_base.rb:24:in `template'
        16: from /app/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2.2/lib/rails/generators/named_base.rb:45:in `inside_template'
        15: from /app/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2.2/lib/rails/generators/named_base.rb:25:in `block in template'
        14: from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/actions/file_manipulation.rb:122:in `template'
        13: from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/actions/create_file.rb:25:in `create_file'
        12: from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/actions.rb:94:in `action'
        11: from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/actions/create_file.rb:60:in `invoke!'
        10: from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/actions/empty_directory.rb:115:in `invoke_with_conflict_check'
         9: from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/actions/create_file.rb:73:in `on_conflict_behavior'
         8: from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/actions/create_file.rb:46:in `identical?'
         7: from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/actions/create_file.rb:53:in `render'
         6: from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/actions/file_manipulation.rb:131:in `block in template'
         5: from /root/.rbenv/versions/2.6.6/lib/ruby/2.6.0/erb.rb:901:in `result'
         4: from /root/.rbenv/versions/2.6.6/lib/ruby/2.6.0/erb.rb:901:in `eval'
         3: from /app/vendor/bundle/ruby/2.6.0/gems/administrate-0.13.0/lib/generators/administrate/dashboard/templates/dashboard.rb.erb:11:in `template'
         2: from /app/vendor/bundle/ruby/2.6.0/gems/administrate-0.13.0/lib/generators/administrate/dashboard/dashboard_generator.rb:53:in `attributes'
         1: from /app/vendor/bundle/ruby/2.6.0/gems/administrate-0.13.0/lib/generators/administrate/dashboard/dashboard_generator.rb:119:in `klass'
/app/vendor/bundle/ruby/2.6.0/gems/administrate-0.13.0/lib/generators/administrate/dashboard/dashboard_generator.rb:119:in `const_get': uninitialized constant Dashboard (NameError)
```

* What versions are you running?
  - Rails `6.0.2.2`
  - administrate `0.13.0`

**Comment by nickcharlton** [comment]
Is this a new Rails app, or one which already has existing models? What do they look like?

Have you tried restarting Spring after installing?

**Comment by pablobm** [comment]
Looking at the error `uninitialized constant Dashboard (NameError)`, and working back from there, it would appear as though `Administrate::Namespace#all_routes` is finding something that it's not able to parse correctly.

Would you be able to share your routes file? If not, could you try removing part of it, a bit at a time, and see if you find which route may possibly be causing this, if any?

**Comment by mshappe** [comment]
@nickcharlton That was the first thing I tried :smile: Because, you know, Spring.

@pablobm I can't paste the routes file here--this is not OSS code, alas--but I can experiment with eliminating things from the routes file (or temporarily slotting in a blank one to see what occurs).

The most obvious culprit is that we're attempting to ADD this gem IN ADDITION to activeadmin, so that we can contemplate a piece-by-piece migration rather than an all-or-nothing one. It's possible I should have led with that, since that may be an obvious "no can do", although it seems like an obvious use case.

**Comment by pablobm** [comment]
Don't worry about `administrate:install`: it's optional. All it does is try to detect your current resource routes and create dashboards for them. You can instead create dashboards one by one, manually or with the `administrate:dashboard` generator.

As for the namespace `admin`, it should also be optional. Change it to something else and it should work. Having said that, we have had some bugs on this in the past, so let us know if you have any issues.

**Comment by nickcharlton** [comment]
Yeah — the `Admin` namespace was a often requested feature and you can change that by doing something like: `rails generate administrate:install --namespace=supervisor`

I'm going to rename this issue to focus on inter-operability with `ActiveAdmin` as I think that's something perhaps interesting on it's own.

If you have other issues with the generators, could you open new issues for them? (much like `UsersRoles` whilst might be non-standard it'd be good for Administrate to be able to handle that situation better).

**Comment by nickcharlton** [comment]
I'm going to close this as I don't think trying to maintain compatibility with another admin library is currently an important focus for the project. I understand that people may wish to migrate from one to another and I think it'd be helpful to have new issues in the future where solutions like changing the namespace aren't enough.
