### ISSUE TITLE
administrate:install fails, unitialized constant

### ISSUE THREAD

**Issue by darkogj** [thoughtbot/administrate#1650]
Using the latest version of Ruby/Rails/administrate. This is frustrating, I have a model named "Niche", when running `administrate:install`, it created a dashboard file called `dashboards/nich_dashboard` and it gave me an error:

```
        68: from -e:1:in `<main>'
        67: from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        66: from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        65: from /usr/local/lib/ruby/gems/2.7.0/gems/spring-2.1.0/lib/spring/application/boot.rb:19:in `<top (required)>'
        64: from /usr/local/lib/ruby/gems/2.7.0/gems/spring-2.1.0/lib/spring/application.rb:139:in `run'
        63: from /usr/local/lib/ruby/gems/2.7.0/gems/spring-2.1.0/lib/spring/application.rb:139:in `loop'
        62: from /usr/local/lib/ruby/gems/2.7.0/gems/spring-2.1.0/lib/spring/application.rb:145:in `block in run'
        61: from /usr/local/lib/ruby/gems/2.7.0/gems/spring-2.1.0/lib/spring/application.rb:175:in `serve'
        60: from /usr/local/lib/ruby/gems/2.7.0/gems/spring-2.1.0/lib/spring/application.rb:175:in `fork'
        59: from /usr/local/lib/ruby/gems/2.7.0/gems/spring-2.1.0/lib/spring/application.rb:215:in `block in serve'
        58: from /usr/local/lib/ruby/gems/2.7.0/gems/spring-2.1.0/lib/spring/command_wrapper.rb:38:in `call'
        57: from /usr/local/lib/ruby/gems/2.7.0/gems/spring-2.1.0/lib/spring/commands/rails.rb:6:in `call'
        56: from /usr/local/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
        55: from /usr/local/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
        54: from /mnt/c/Users/Darko/RubymineProjects/acquisition/bin/rails:9:in `<main>'
        53: from /usr/local/lib/ruby/gems/2.7.0/gems/zeitwerk-2.3.0/lib/zeitwerk/kernel.rb:23:in `require'
        52: from /usr/local/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        51: from /usr/local/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        50: from /usr/local/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        49: from /usr/local/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        48: from /usr/local/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        47: from /usr/local/lib/ruby/gems/2.7.0/gems/railties-6.0.3/lib/rails/commands.rb:18:in `<main>'
        46: from /usr/local/lib/ruby/gems/2.7.0/gems/railties-6.0.3/lib/rails/command.rb:46:in `invoke'
        45: from /usr/local/lib/ruby/gems/2.7.0/gems/railties-6.0.3/lib/rails/command/base.rb:69:in `perform'
        44: from /usr/local/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        43: from /usr/local/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        42: from /usr/local/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        41: from /usr/local/lib/ruby/gems/2.7.0/gems/railties-6.0.3/lib/rails/commands/generate/generate_command.rb:26:in `perform'
        40: from /usr/local/lib/ruby/gems/2.7.0/gems/railties-6.0.3/lib/rails/generators.rb:276:in `invoke'
        39: from /usr/local/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
        38: from /usr/local/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/group.rb:232:in `dispatch'
        37: from /usr/local/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `invoke_all'
        36: from /usr/local/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `map'
        35: from /usr/local/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `each'
        34: from /usr/local/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `block in invoke_all'
        33: from /usr/local/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        32: from /usr/local/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        31: from /usr/local/lib/ruby/gems/2.7.0/gems/administrate-0.13.0/lib/generators/administrate/install/install_generator.rb:28:in `run_dashboard_generators'
        30: from /usr/local/lib/ruby/gems/2.7.0/gems/administrate-0.13.0/lib/generators/administrate/install/install_generator.rb:28:in `each'
        29: from /usr/local/lib/ruby/gems/2.7.0/gems/administrate-0.13.0/lib/generators/administrate/install/install_generator.rb:29:in `block in run_dashboard_generators'
        28: from /usr/local/lib/ruby/gems/2.7.0/gems/administrate-0.13.0/lib/administrate/generator_helpers.rb:4:in `call_generator'
        27: from /usr/local/lib/ruby/gems/2.7.0/gems/railties-6.0.3/lib/rails/generators.rb:276:in `invoke'
        26: from /usr/local/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
        25: from /usr/local/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/group.rb:232:in `dispatch'
        24: from /usr/local/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `invoke_all'
        23: from /usr/local/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `map'
        22: from /usr/local/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `each'
        21: from /usr/local/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `block in invoke_all'
        20: from /usr/local/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        19: from /usr/local/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        18: from /usr/local/lib/ruby/gems/2.7.0/gems/administrate-0.13.0/lib/generators/administrate/dashboard/dashboard_generator.rb:32:in `create_dashboard_definition'
        17: from /usr/local/lib/ruby/gems/2.7.0/gems/railties-6.0.3/lib/rails/generators/named_base.rb:24:in `template'
        16: from /usr/local/lib/ruby/gems/2.7.0/gems/railties-6.0.3/lib/rails/generators/named_base.rb:45:in `inside_template'
        15: from /usr/local/lib/ruby/gems/2.7.0/gems/railties-6.0.3/lib/rails/generators/named_base.rb:25:in `block in template'
        14: from /usr/local/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/actions/file_manipulation.rb:122:in `template'
        13: from /usr/local/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/actions/create_file.rb:25:in `create_file'
        12: from /usr/local/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/actions.rb:93:in `action'
        11: from /usr/local/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/actions/create_file.rb:60:in `invoke!'
        10: from /usr/local/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/actions/empty_directory.rb:115:in `invoke_with_conflict_check'
         9: from /usr/local/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/actions/create_file.rb:73:in `on_conflict_behavior'
         8: from /usr/local/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/actions/create_file.rb:46:in `identical?'
         7: from /usr/local/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/actions/create_file.rb:53:in `render'
         6: from /usr/local/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/actions/file_manipulation.rb:131:in `block in template'
         5: from /usr/local/lib/ruby/2.7.0/erb.rb:905:in `result'
         4: from /usr/local/lib/ruby/2.7.0/erb.rb:905:in `eval'
         3: from /usr/local/lib/ruby/gems/2.7.0/gems/administrate-0.13.0/lib/generators/administrate/dashboard/templates/dashboard.rb.erb:11:in `template'
         2: from /usr/local/lib/ruby/gems/2.7.0/gems/administrate-0.13.0/lib/generators/administrate/dashboard/dashboard_generator.rb:53:in `attributes'
         1: from /usr/local/lib/ruby/gems/2.7.0/gems/administrate-0.13.0/lib/generators/administrate/dashboard/dashboard_generator.rb:119:in `klass'
/usr/local/lib/ruby/gems/2.7.0/gems/administrate-0.13.0/lib/generators/administrate/dashboard/dashboard_generator.rb:119:in `const_get': uninitialized constant Nich (NameError)
`
  - Rails
  - administrate
```

This is 100% new Rails installation, and I can't find what's going on from the stack trace itself. How did Administrate figure out to shorten my model and call it "Nich"?

**Comment by darkogj** [comment]
Just an update, renamed the model, and everything was okay

**Comment by pablobm** [comment]
Thank you for mentioning the nich/niche/niches problem. It's probably down to Administrate doing one too many singularisation/pluralisation, combined with an edge case of Rails's inflection rules. I'll look into it.

**Comment by pablobm** [comment]
I had a quick look. This is the problem at the moment:

1. The generator looks at the routes and sees that "niches" is a resource.
2. It applies `#singularize` to get the name of the model.
3. Due to the rules applied by Rails's inflector, this yields "nich".

```
> "niches".singularize
=> "nich"
```

This is a relatively common problem with certain words. English (like many other languages) has many words with irregular singularization/pluralization rules, and it's difficult for software to figure them out. You may see this in any type of Rails app, not just with Administrate. In general, it's recommended that projects that use these problematic words tell Rails about them. For example:

```
ActiveSupport::Inflector.inflections(:en) do |inflect|
  inflect.irregular 'niche', 'niches'
end
"niches".singularize
# => "niche"
```

As for what Administrate can do to better handle this, two options spring to mind:

1. Handle this error to show a more understandable message to the user. Eg: "Saw resource `niches`, and assumed that a model `Nich` would exist. However it couldn't be found.`
2. Make a larger change to the way resource names are resolved within Administrate.

These solutions are non-exclusive: both can happen.

Unfortunately, we don't have much time at the moment work on either, and generators are a relatively low priority. We'd welcome PRs, particularly for option 1, as option 2 would involve a larger refactor that I've had in mind for a while, but it's difficult to accomplish.

**Comment by nickcharlton** [comment]
Yeah — I'd support something around option 1. The initial install experience capturing some of these cases would be good and I think such a thing would help to ensure any refactoring we did do would have test coverage around that.
