### ISSUE TITLE
HasMany breaks on show when the associated object has a BelongTo field on the index

### ISSUE THREAD

**Issue by dgmstuart** [thoughtbot/administrate#1761]
* What were you trying to do?

Here's an invented example to demonstrate the problem:
- `Book`s are written by `Author`s and published by `Publisher`s
- We want to show the names of the `Author` and `Publisher` on the `Books#index` page _(this works fine)_
- We also want to show the list of books written by an author, on their `Authors#show` page. (_**this breaks**_)

```ruby
class AuthorDashboard
  ATTRIBUTE_TYPES = {
    books: Field::HasMany,
    first_name: Field::String,
    last_name: Field::String
  }
  
  SHOW_PAGE_ATTRIBUTES = %i[
    books
  ]

  def display_resource(order)
    " #{author.first_name} #{author.last_name}"
  end
end

class PublisherDashboard
  ATTRIBUTE_TYPES = {
    name: Field::String,
  }

  def display_resource(publisher)
    publisher.name
  end
end

class BooksDashboard
  ATTRIBUTE_TYPES = {
    author: Field::BelongsTo,
    publisher: Field::BelongsTo
  }
  
  COLLECTION_ATTRIBUTES = %i[
    author
    publisher
  ]
end
```

All of the views work fine, except the `Authors#show` page: it fails with 

    NoMethodError in Admin::Authors#show undefined method `name' for #<Author:0x00007f8761f41bf0>

What seems to be happening is that it's trying to render the rows of the collection view, but when it's coming to render the `Publisher` record, it's rendering the `Author` record instead.

More specifically: the `BelongsTo` field for the `Author` (ie. the current page) is getting passed where the the field for the `Publisher` should be getting passed instead.

I've done some `pry`-ing in the gem running on my local machine and I can't work out why this is happening yet. I'm very happy to pull a PR together if someone can point me in the right direction by explaining how these fields are looked up.

* What versions are you running?
  - Rails 6.0.3.3
  - Ruby 2.7.1
  - administrate 0.14.0

**Comment by dgmstuart** [comment]
Seems like `collection_presenter.attributes_for(resource).each` is returning the wrong thing?

It has an attribute of `:publisher`, but the data is an `Author`

I also noticed that the `attribute_types` entry for `:publisher` when rendering this page has a type of `Administrate::Field::Deferred` - not sure what it means, but I'm wondering if the issue is that when this gets 'resolved' to a proper field, it's building it incorrectly.

**Comment by dgmstuart** [comment]
OK I've tracked it down further:

``` ruby 
# lib/administrate/page/base.rb`
def get_attribute_value(resource, attribute_name)
  resource.public_send(attribute_name)
end
```
...in which the resource is a `Book` and the `attribute_name` is `:publisher`.... but it returns the Author with the same ID as the publisher!

There's something pretty funky going on here. 

There is some complexity that the relationships between Books and Authors/publishers are not via normal Rails IDs - they're matched based an external ID. But I've tried experimenting with the same records in the console and they behave as expected.

**Comment by dgmstuart** [comment]
It could be because the actual name of the `Author` model in my application is `Order` - so maybe a name-clash with `Administrate::Order` somewhere, but I don't see how that's possible, and I don't think it would explain this behaviour? Also I see that the test suite has a dashboard called `Order`.

**Comment by pablobm** [comment]
There's every chance that the problem is the model name (`Order` as opposed to the `Author` example). Having said that, our example app (the one that runs with `rails s` in the codebase) does have an `Order` model and I would have hoped we had fixed this sort of issues.

Would you be able to post the actual stack trace, with the real file paths?

**Comment by dgmstuart** [comment]
Looking at the example app, I can't seem to tweak it in such a way that the test fails. It seems like spec/features/orders_show_spec.rb should be able to reproduce the error if I change the definition of `OrderDashboard#display_resource`, but it passes fine 🤔 

Stack trace on my app in development from visiting the Order show page: 
```
activemodel (6.0.3.3) lib/active_model/attribute_methods.rb:432:in `method_missing'
app/dashboards/hotel_dashboard.rb:47:in `display_resource'
administrate (0.14.0) lib/administrate/field/associative.rb:7:in `display_associated_resource'
administrate (0.14.0) app/views/fields/belongs_to/_index.html.erb:21
actionview (6.0.3.3) lib/action_view/base.rb:274:in `_run'
actionview (6.0.3.3) lib/action_view/template.rb:185:in `block in render'
activesupport (6.0.3.3) lib/active_support/notifications.rb:182:in `instrument'
actionview (6.0.3.3) lib/action_view/template.rb:385:in `instrument_render_template'
actionview (6.0.3.3) lib/action_view/template.rb:183:in `render'
actionview (6.0.3.3) lib/action_view/renderer/partial_renderer.rb:357:in `block in render_partial'
actionview (6.0.3.3) lib/action_view/renderer/abstract_renderer.rb:88:in `block in instrument'
activesupport (6.0.3.3) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.3.3) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.3.3) lib/active_support/notifications.rb:180:in `instrument'
actionview (6.0.3.3) lib/action_view/renderer/abstract_renderer.rb:87:in `instrument'
actionview (6.0.3.3) lib/action_view/renderer/partial_renderer.rb:346:in `render_partial'
actionview (6.0.3.3) lib/action_view/renderer/partial_renderer.rb:317:in `render'
actionview (6.0.3.3) lib/action_view/renderer/renderer.rb:65:in `render_partial_to_object'
actionview (6.0.3.3) lib/action_view/renderer/renderer.rb:27:in `render_to_object'
actionview (6.0.3.3) lib/action_view/renderer/renderer.rb:22:in `render'
actionview (6.0.3.3) lib/action_view/helpers/rendering_helper.rb:34:in `block in render'
actionview (6.0.3.3) lib/action_view/base.rb:304:in `in_rendering_context'
actionview (6.0.3.3) lib/action_view/helpers/rendering_helper.rb:30:in `render'
administrate (0.14.0) app/helpers/administrate/application_helper.rb:15:in `render_field'
administrate (0.14.0) app/views/administrate/application/_collection.html.erb:69
administrate (0.14.0) app/views/administrate/application/_collection.html.erb:62:in `each'
administrate (0.14.0) app/views/administrate/application/_collection.html.erb:62
activerecord (6.0.3.3) lib/active_record/relation/delegation.rb:87:in `each'
activerecord (6.0.3.3) lib/active_record/relation/delegation.rb:87:in `each'
administrate (0.14.0) app/views/administrate/application/_collection.html.erb:56
actionview (6.0.3.3) lib/action_view/base.rb:274:in `_run'
actionview (6.0.3.3) lib/action_view/template.rb:185:in `block in render'
activesupport (6.0.3.3) lib/active_support/notifications.rb:182:in `instrument'
actionview (6.0.3.3) lib/action_view/template.rb:385:in `instrument_render_template'
actionview (6.0.3.3) lib/action_view/template.rb:183:in `render'
actionview (6.0.3.3) lib/action_view/renderer/partial_renderer.rb:357:in `block in render_partial'
actionview (6.0.3.3) lib/action_view/renderer/abstract_renderer.rb:88:in `block in instrument'
activesupport (6.0.3.3) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.3.3) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.3.3) lib/active_support/notifications.rb:180:in `instrument'
actionview (6.0.3.3) lib/action_view/renderer/abstract_renderer.rb:87:in `instrument'
actionview (6.0.3.3) lib/action_view/renderer/partial_renderer.rb:346:in `render_partial'
actionview (6.0.3.3) lib/action_view/renderer/partial_renderer.rb:317:in `render'
actionview (6.0.3.3) lib/action_view/renderer/renderer.rb:65:in `render_partial_to_object'
actionview (6.0.3.3) lib/action_view/renderer/renderer.rb:53:in `render_partial'
actionview (6.0.3.3) lib/action_view/helpers/rendering_helper.rb:38:in `render'
administrate (0.14.0) app/views/fields/has_many/_show.html.erb:24
actionview (6.0.3.3) lib/action_view/base.rb:274:in `_run'
actionview (6.0.3.3) lib/action_view/template.rb:185:in `block in render'
activesupport (6.0.3.3) lib/active_support/notifications.rb:182:in `instrument'
actionview (6.0.3.3) lib/action_view/template.rb:385:in `instrument_render_template'
actionview (6.0.3.3) lib/action_view/template.rb:183:in `render'
actionview (6.0.3.3) lib/action_view/renderer/partial_renderer.rb:357:in `block in render_partial'
actionview (6.0.3.3) lib/action_view/renderer/abstract_renderer.rb:88:in `block in instrument'
activesupport (6.0.3.3) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.3.3) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.3.3) lib/active_support/notifications.rb:180:in `instrument'
actionview (6.0.3.3) lib/action_view/renderer/abstract_renderer.rb:87:in `instrument'
actionview (6.0.3.3) lib/action_view/renderer/partial_renderer.rb:346:in `render_partial'
actionview (6.0.3.3) lib/action_view/renderer/partial_renderer.rb:317:in `render'
actionview (6.0.3.3) lib/action_view/renderer/renderer.rb:65:in `render_partial_to_object'
actionview (6.0.3.3) lib/action_view/renderer/renderer.rb:27:in `render_to_object'
actionview (6.0.3.3) lib/action_view/renderer/renderer.rb:22:in `render'
actionview (6.0.3.3) lib/action_view/helpers/rendering_helper.rb:34:in `block in render'
actionview (6.0.3.3) lib/action_view/base.rb:304:in `in_rendering_context'
actionview (6.0.3.3) lib/action_view/helpers/rendering_helper.rb:30:in `render'
administrate (0.14.0) app/helpers/administrate/application_helper.rb:15:in `render_field'
administrate (0.14.0) app/views/administrate/application/show.html.erb:46
administrate (0.14.0) app/views/administrate/application/show.html.erb:37:in `each'
administrate (0.14.0) app/views/administrate/application/show.html.erb:37
actionview (6.0.3.3) lib/action_view/base.rb:274:in `_run'
actionview (6.0.3.3) lib/action_view/template.rb:185:in `block in render'
activesupport (6.0.3.3) lib/active_support/notifications.rb:182:in `instrument'
actionview (6.0.3.3) lib/action_view/template.rb:385:in `instrument_render_template'
actionview (6.0.3.3) lib/action_view/template.rb:183:in `render'
actionview (6.0.3.3) lib/action_view/renderer/template_renderer.rb:58:in `block (2 levels) in render_template'
actionview (6.0.3.3) lib/action_view/renderer/abstract_renderer.rb:88:in `block in instrument'
activesupport (6.0.3.3) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.3.3) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.3.3) lib/active_support/notifications.rb:180:in `instrument'
actionview (6.0.3.3) lib/action_view/renderer/abstract_renderer.rb:87:in `instrument'
actionview (6.0.3.3) lib/action_view/renderer/template_renderer.rb:57:in `block in render_template'
actionview (6.0.3.3) lib/action_view/renderer/template_renderer.rb:65:in `render_with_layout'
actionview (6.0.3.3) lib/action_view/renderer/template_renderer.rb:56:in `render_template'
actionview (6.0.3.3) lib/action_view/renderer/template_renderer.rb:13:in `render'
actionview (6.0.3.3) lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
actionview (6.0.3.3) lib/action_view/renderer/renderer.rb:29:in `render_to_object'
actionview (6.0.3.3) lib/action_view/rendering.rb:117:in `block in _render_template'
actionview (6.0.3.3) lib/action_view/base.rb:304:in `in_rendering_context'
actionview (6.0.3.3) lib/action_view/rendering.rb:116:in `_render_template'
actionpack (6.0.3.3) lib/action_controller/metal/streaming.rb:218:in `_render_template'
actionview (6.0.3.3) lib/action_view/rendering.rb:103:in `render_to_body'
actionpack (6.0.3.3) lib/action_controller/metal/rendering.rb:52:in `render_to_body'
actionpack (6.0.3.3) lib/action_controller/metal/renderers.rb:142:in `render_to_body'
actionpack (6.0.3.3) lib/abstract_controller/rendering.rb:25:in `render'
actionpack (6.0.3.3) lib/action_controller/metal/rendering.rb:36:in `render'
actionpack (6.0.3.3) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
activesupport (6.0.3.3) lib/active_support/core_ext/benchmark.rb:14:in `block in ms'
/Users/dgmstuart/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
activesupport (6.0.3.3) lib/active_support/core_ext/benchmark.rb:14:in `ms'
actionpack (6.0.3.3) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
actionpack (6.0.3.3) lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
activerecord (6.0.3.3) lib/active_record/railties/controller_runtime.rb:34:in `cleanup_view_runtime'
actionpack (6.0.3.3) lib/action_controller/metal/instrumentation.rb:43:in `render'
administrate (0.14.0) app/controllers/administrate/application_controller.rb:24:in `show'
actionpack (6.0.3.3) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (6.0.3.3) lib/abstract_controller/base.rb:195:in `process_action'
actionpack (6.0.3.3) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (6.0.3.3) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (6.0.3.3) lib/active_support/callbacks.rb:135:in `run_callbacks'
actionpack (6.0.3.3) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (6.0.3.3) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (6.0.3.3) lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
activesupport (6.0.3.3) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.3.3) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.3.3) lib/active_support/notifications.rb:180:in `instrument'
actionpack (6.0.3.3) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (6.0.3.3) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
activerecord (6.0.3.3) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
actionpack (6.0.3.3) lib/abstract_controller/base.rb:136:in `process'
actionview (6.0.3.3) lib/action_view/rendering.rb:39:in `process'
actionpack (6.0.3.3) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (6.0.3.3) lib/action_controller/metal.rb:254:in `dispatch'
actionpack (6.0.3.3) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (6.0.3.3) lib/action_dispatch/routing/route_set.rb:33:in `serve'
actionpack (6.0.3.3) lib/action_dispatch/journey/router.rb:49:in `block in serve'
actionpack (6.0.3.3) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.0.3.3) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.0.3.3) lib/action_dispatch/routing/route_set.rb:834:in `call'
rack-attack (6.3.1) lib/rack/attack.rb:111:in `call'
clearance (2.3.0) lib/clearance/rack_session.rb:23:in `call'
rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.3) lib/rack/etag.rb:27:in `call'
rack (2.2.3) lib/rack/conditional_get.rb:27:in `call'
rack (2.2.3) lib/rack/head.rb:12:in `call'
actionpack (6.0.3.3) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (6.0.3.3) lib/action_dispatch/middleware/cookies.rb:648:in `call'
activerecord (6.0.3.3) lib/active_record/migration.rb:567:in `call'
actionpack (6.0.3.3) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.3.3) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.3.3) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.3.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.3) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
appsignal (2.11.0) lib/appsignal/rack/rails_instrumentation.rb:19:in `call'
actionpack (6.0.3.3) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.3.3) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.3) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.3) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.3) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.3) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.3) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.3) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (6.0.3.3) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.3) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.3) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.3) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.3) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
webpacker (5.2.1) lib/webpacker/dev_server_proxy.rb:25:in `perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
railties (6.0.3.3) lib/rails/engine.rb:527:in `call'
puma (4.3.6) lib/puma/configuration.rb:228:in `call'
puma (4.3.6) lib/puma/server.rb:713:in `handle_request'
puma (4.3.6) lib/puma/server.rb:472:in `process_client'
puma (4.3.6) lib/puma/server.rb:328:in `block in run'
puma (4.3.6) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```

**Comment by pablobm** [comment]
I'm having several problems here. First, it's difficult to translate between the "real" code (with hotels and orders) and the example code (with books and authors).

Second, I wonder if something has been lost in translation when creating the example. For instance, the following code is wrong:

```ruby
  def display_resource(order)
    " #{author.first_name} #{author.last_name}"
  end
```

The argument is `order`, but it should be `author`. It's a small thing and I can get over it, but it raises the question of whether the example code runs, and if it's actually comparable to the real one.

Having said that, you mention that the following code doesn't behave as expected:

```ruby
# lib/administrate/page/base.rb
def get_attribute_value(resource, attribute_name)
  resource.public_send(attribute_name)
end
```

If `resource` and `attribute_name` are the right thing (are they?), then this code is perfectly legitimate. It should do whatever Rails does in that case. So for example, try this:

```ruby
# lib/administrate/page/base.rb
def get_attribute_value(resource, attribute_name)
  val = resource.public_send(attribute_name)
  pp [resource, attribute_name, val]
  val
end
```

Does it always print out the expected result for the given arguments? If it does anything funky, to me it suggests that there's something funky in the DB relationships, or perhaps in the definitions of the associations. You mention a non-standard id. How non-standard is it? If it's just an id number/string, then it's fine, it shouldn't affect this at all. Rails doesn't care how the number was generated, as long as it matches the foreign key.

Have a look and let us know.

**Comment by pablobm** [comment]
Closing due to lack of activity. Happy to reopen if there's more feedback.
