### ISSUE TITLE
HasOne field breaks when rendering a nested HasMany

### ISSUE THREAD

**Issue by pablobm** [thoughtbot/administrate#1792]
Given:
  * Player has_one Ball
  * Ball has_many Patches

  * Player dashboard has a :ball attribute (Field::HasOne)
  * Ball dashboard has a :patch attribute (Field::HasMany)

When:
  * Rendering player#show

Then:
  * Kaboom! (see trace)

```
 Showing $PWD/app/views/fields/has_many/_show.html.erb where line #28 raised:

undefined local variable or method `page' for #<#<Class:0x0000563fcc3bc920>:0x0000563fcc3c1fb0>

Extracted source (around line #28):

26    collection_presenter: field.associated_collection(order),
27    collection_field_name: field.name,
28    page: page,
29    resources: field.resources(page_number, order),
30    table_title: field.name,
31  ) %>

Trace of template inclusion: #<ActionView::Template $PWD/app/views/fields/has_one/_show.html.erb locals=["field", "page"]>, #<ActionView::Template $PWD/app/views/administrate/application/show.html.erb locals=["page"]>

Rails.root: $PWD/spec/example_app
Application Trace | Framework Trace | Full Trace
$PWD/app/views/fields/has_many/_show.html.erb:28
(...Rails trace...)
$PWD/app/helpers/administrate/application_helper.rb:16:in `render_field'
$PWD/app/views/fields/has_one/_show.html.erb:35
$PWD/app/views/fields/has_one/_show.html.erb:26:in `each'
$PWD/app/views/fields/has_one/_show.html.erb:26
(...Rails trace...)
$PWD/app/helpers/administrate/application_helper.rb:16:in `render_field'
$PWD/app/views/administrate/application/show.html.erb:46
$PWD/app/views/administrate/application/show.html.erb:37:in `each'
$PWD/app/views/administrate/application/show.html.erb:37
(...Rails trace...)
/home/pablobm/Documents/projects/laptop/repos/asdf/installs/ruby/2.6.5/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
(...Rails trace...)
$PWD/app/controllers/administrate/application_controller.rb:24:in `show'
(...Rails trace...)
```

This can be reproduced in the example app if we add the following (which is a bit artificial, but serves this purpose):

```ruby
### /spec/example_app/app/models/product.rb
  has_one :line_item
  has_one :order, through: :line_item
```

```ruby
### spec/example_app/app/dashboards/product_dashboard.rb
  ATTRIBUTES = {
    ...,
    :order,
    ...
  }

  ...

  ATTRIBUTE_TYPES = {
    ...,
    order: Field::HasOne,
    ...
  }
```

Tested with:
  * Administrate 02a15fc (post v0.14)
  * Rails 6.0.3.3

Note that this doesn't happen with v0.14, so it must be something introduced recently. Even in this case, it doesn't render perfectly (the HasMany field is not correct), but at least doesn't break.

**Comment by nickcharlton** [comment]
Does #1788 help here?

It seems like me merging in #1259 caused this.

**Comment by pablobm** [comment]
It does look like the same thing! I'll close this issue.
