### ISSUE TITLE
Error on running "generate administrate:install"

### ISSUE THREAD

**Issue by mmalivuk** [thoughtbot/administrate#1817]
Hello,

Upon running the "rails generate administrate:install" command I'm presented with the following:

```
Running via Spring preloader in process 48847
Traceback (most recent call last):
        53: from -e:1:in `<main>'
        52: from /Users/mm/.rbenv/versions/2.7.1/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        51: from /Users/mm/.rbenv/versions/2.7.1/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        50: from /Users/mm/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/application/boot.rb:19:in `<top (required)>'
        49: from /Users/mm/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `run'
        48: from /Users/mm/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `loop'
        47: from /Users/mm/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/application.rb:145:in `block in run'
        46: from /Users/mm/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/application.rb:180:in `serve'
        45: from /Users/mm/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/application.rb:180:in `fork'
        44: from /Users/mm/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/application.rb:220:in `block in serve'
        43: from /Users/mm/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/command_wrapper.rb:38:in `call'
        42: from /Users/mm/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/commands/rails.rb:6:in `call'
        41: from /Users/mm/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
        40: from /Users/mm/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
        39: from /Users/mm/Development/lemma-rails/bin/rails:9:in `<main>'
        38: from /Users/mm/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.1/lib/zeitwerk/kernel.rb:33:in `require'
        37: from /Users/mm/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        36: from /Users/mm/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        35: from /Users/mm/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        34: from /Users/mm/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        33: from /Users/mm/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        32: from /Users/mm/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/railties-6.0.3.4/lib/rails/commands.rb:18:in `<main>'
        31: from /Users/mm/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/railties-6.0.3.4/lib/rails/command.rb:46:in `invoke'
        30: from /Users/mm/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/railties-6.0.3.4/lib/rails/command/base.rb:69:in `perform'
        29: from /Users/mm/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        28: from /Users/mm/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        27: from /Users/mm/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        26: from /Users/mm/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/railties-6.0.3.4/lib/rails/commands/generate/generate_command.rb:26:in `perform'
        25: from /Users/mm/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/railties-6.0.3.4/lib/rails/generators.rb:276:in `invoke'
        24: from /Users/mm/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
        23: from /Users/mm/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/group.rb:232:in `dispatch'
        22: from /Users/mm/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `invoke_all'
        21: from /Users/mm/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `map'
        20: from /Users/mm/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `each'
        19: from /Users/mm/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `block in invoke_all'
        18: from /Users/mm/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        17: from /Users/mm/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        16: from /Users/mm/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/administrate-c879e75ae49c/lib/generators/administrate/install/install_generator.rb:15:in `run_routes_generator'
        15: from /Users/mm/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/administrate-c879e75ae49c/lib/administrate/generator_helpers.rb:4:in `call_generator'
        14: from /Users/mm/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/railties-6.0.3.4/lib/rails/generators.rb:276:in `invoke'
        13: from /Users/mm/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
        12: from /Users/mm/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/group.rb:232:in `dispatch'
        11: from /Users/mm/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `invoke_all'
        10: from /Users/mm/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `map'
         9: from /Users/mm/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `each'
         8: from /Users/mm/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `block in invoke_all'
         7: from /Users/mm/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
         6: from /Users/mm/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
         5: from /Users/mm/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/administrate-c879e75ae49c/lib/generators/administrate/routes/routes_generator.rb:23:in `insert_dashboard_routes'
         4: from /Users/mm/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/administrate-c879e75ae49c/lib/generators/administrate/routes/routes_generator.rb:98:in `should_route_dashboard?'
         3: from /Users/mm/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/administrate-c879e75ae49c/lib/generators/administrate/routes/routes_generator.rb:86:in `routes_includes_resources?'
         2: from /Users/mm/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/administrate-c879e75ae49c/lib/generators/administrate/routes/routes_generator.rb:90:in `rails_routes_file_path'
         1: from /Users/mm/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/administrate-c879e75ae49c/lib/administrate/generator_helpers.rb:10:in `find_routes_file'
/Users/mm/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/administrate-c879e75ae49c/lib/administrate/generator_helpers.rb:24:in `find_file': uninitialized constant Administrate::GeneratorHelpers::Find (NameError)
```

I've tried re bundling, reinstalling the gem, trying spring stop, with no luck. Appreciate any help.

**Comment by pablobm** [comment]
There appears to be a problem in the order in which things are loaded. The module raising the error depends on the library `find`, but sometimes it's not loaded when the code gets there.

This should now be fixed in `master`, after merging https://github.com/thoughtbot/administrate/pull/1782

From your backtrace, it looks like you may be using a forked version of Administrate. Is this correct? If so, try rebasing and forking from the latest `master` and this should solve your issue.

I'm going to close this issue for now, as it should be solved in the next version. Please let us know if there's anything else.
