### ISSUE TITLE
undefined method `klass' for nil:NilClass (NoMethodError)`

### ISSUE THREAD

**Issue by WWGate** [thoughtbot/administrate#1830]
* What were you trying to do?
Installing administrate gem
* What did you end up with (logs, or, even better, example apps are great!)?

```
Traceback (most recent call last):
        68: from -e:1:in `<main>'
        67: from /home/fadi/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        66: from /home/fadi/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        65: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
        64: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
        63: from /mnt/c/development/sites/joody/bin/rails:9:in `<main>'
        62: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/zeitwerk-2.4.0/lib/zeitwerk/kernel.rb:34:in `require'
        61: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        60: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        59: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        58: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        57: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        56: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/railties-6.0.3.4/lib/rails/commands.rb:18:in `<main>'
        55: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/railties-6.0.3.4/lib/rails/command.rb:46:in `invoke'
        54: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/railties-6.0.3.4/lib/rails/command/base.rb:69:in `perform'
        53: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        52: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        51: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        50: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/railties-6.0.3.4/lib/rails/commands/generate/generate_command.rb:26:in `perform'
        49: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/railties-6.0.3.4/lib/rails/generators.rb:276:in `invoke'
        48: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
        47: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/thor-1.0.1/lib/thor/group.rb:232:in `dispatch'
        46: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `invoke_all'
        45: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `map'
        44: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `each'
        43: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `block in invoke_all'
        42: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        41: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        40: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/administrate-0.14.0/lib/generators/administrate/install/install_generator.rb:28:in `run_dashboard_generators'
        39: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/administrate-0.14.0/lib/generators/administrate/install/install_generator.rb:28:in `each'
        38: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/administrate-0.14.0/lib/generators/administrate/install/install_generator.rb:29:in `block in run_dashboard_generators'
        37: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/administrate-0.14.0/lib/administrate/generator_helpers.rb:4:in `call_generator'
        36: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/railties-6.0.3.4/lib/rails/generators.rb:276:in `invoke'
        35: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
        34: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/thor-1.0.1/lib/thor/group.rb:232:in `dispatch'
        33: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `invoke_all'
        32: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `map'
        31: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `each'
        30: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `block in invoke_all'
        29: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        28: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        27: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/administrate-0.14.0/lib/generators/administrate/dashboard/dashboard_generator.rb:34:in `create_dashboard_definition'
        26: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/railties-6.0.3.4/lib/rails/generators/named_base.rb:24:in `template'
        25: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/railties-6.0.3.4/lib/rails/generators/named_base.rb:45:in `inside_template'
        24: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/railties-6.0.3.4/lib/rails/generators/named_base.rb:25:in `block in template'
        23: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/thor-1.0.1/lib/thor/actions/file_manipulation.rb:122:in `template'
        22: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/thor-1.0.1/lib/thor/actions/create_file.rb:25:in `create_file'
        21: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/thor-1.0.1/lib/thor/actions.rb:93:in `action'
        20: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/thor-1.0.1/lib/thor/actions/create_file.rb:60:in `invoke!'
        19: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/thor-1.0.1/lib/thor/actions/empty_directory.rb:117:in `invoke_with_conflict_check'
        18: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/thor-1.0.1/lib/thor/actions/create_file.rb:63:in `block in invoke!'
        17: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/thor-1.0.1/lib/thor/actions/create_file.rb:63:in `open'
        16: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/thor-1.0.1/lib/thor/actions/create_file.rb:63:in `block (2 levels) in invoke!'
        15: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/thor-1.0.1/lib/thor/actions/create_file.rb:53:in `render'
        14: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/thor-1.0.1/lib/thor/actions/file_manipulation.rb:131:in `block in template'
        13: from /home/fadi/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/erb.rb:905:in `result'
        12: from /home/fadi/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/erb.rb:905:in `eval'
        11: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/administrate-0.14.0/lib/generators/administrate/dashboard/templates/dashboard.rb.erb:11:in `template'
        10: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/administrate-0.14.0/lib/generators/administrate/dashboard/dashboard_generator.rb:57:in `attributes'
         9: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/administrate-0.14.0/lib/generators/administrate/dashboard/dashboard_generator.rb:65:in `redundant_attributes'
         8: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/administrate-0.14.0/lib/generators/administrate/dashboard/dashboard_generator.rb:65:in `flat_map'
         7: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/administrate-0.14.0/lib/generators/administrate/dashboard/dashboard_generator.rb:65:in `each'
         6: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/administrate-0.14.0/lib/generators/administrate/dashboard/dashboard_generator.rb:66:in `block in redundant_attributes'
         5: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/administrate-0.14.0/lib/generators/administrate/dashboard/dashboard_generator.rb:71:in `redundant_attributes_for'
         4: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/administrate-0.14.0/lib/generators/administrate/dashboard/dashboard_generator.rb:112:in `association_type'
         3: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/administrate-0.14.0/lib/generators/administrate/dashboard/dashboard_generator.rb:125:in `relationship_options_string'
         2: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/activerecord-6.0.3.4/lib/active_record/reflection.rb:166:in `class_name'
         1: from /home/fadi/.rvm/gems/ruby-2.7.0/gems/activerecord-6.0.3.4/lib/active_record/reflection.rb:989:in `derive_class_name'
/home/fadi/.rvm/gems/ruby-2.7.0/gems/activerecord-6.0.3.4/lib/active_record/reflection.rb:790:in `source_reflection': undefined method `klass' for nil:NilClass (NoMethodError)`
```

* What versions are you running?
  - Rails 6.0.3
  - administrate 0.14

when I run my app and trying to access admin, I get the following error:

```
Error: Undefined variable: "$bold-font-weight".
        on line 9:16 of app/assets/stylesheets/administrate/base/_forms.scss
>>   font-weight: $bold-font-weight;

   ---------------^
```

so I tried to generate assets manually
and same error is presented

Any idea to solve this please?

**Comment by RaeRachael** [comment]
Hi, not sure how much help I can be. 

It seems like the issue might be how administrate is trying to read the relationships you have in you DB. Perhaps it is trying to read a table that isn't appropriate (not sure if we should be worried about seeing `active_record/reflection` near the end of the stack trace.

Were any files created?

The '`Error: Undefined variable: "$bold-font-weight".
on line 9:16 of app/assets/stylesheets/administrate/base/_forms.scss

font-weight: $bold-font-weight;

---------------^` ' seems like a different problem, would you be able to make a separate issue for that?

**Comment by glenpike** [comment]
As an FYI, I ran into this error trying to generate a dashboard for my model:

```
class Supporter < ApplicationRecord
  has_many :events, through: :event_supporters

  validates :name, presence: true
end
```

I had not added the association for the 'through' table.

This sorted it:

```
class Supporter < ApplicationRecord
  has_many :event_supporters
  has_many :events, through: :event_supporters

  validates :name, presence: true
end
```
(https://guides.rubyonrails.org/association_basics.html#the-has-many-through-association)

**Comment by pablobm** [comment]
Thank you for that hint, @glenpike! That should help others who encounter this issue. As to a proper fix, the code that raises the exception has changed in `master`, so there's a good chance that this won't be a problem starting with the next version of Administrate (or that we have different problems, of course). Therefore I'm going to close this issue. But do let us know if you have more information.
