### ISSUE TITLE
masquerade works on localhost but not on VPS (development mode)

### ISSUE THREAD

**Issue by dvodvo** [thoughtbot/administrate#1878]
On localhost, searching for a user, then calling up the show view and invoking the masquerading function, the application returns and routes to the root_path:
```
Started GET "/users/masquerade/16203?masquerade=syxdpH2UZaHvrzsmpJxBZA&masqueraded_resource_class=User" for ::1 at 2021-01-29 09:21:48 +0100
Processing by Devise::MasqueradesController#show as HTML
  Parameters: {"masquerade"=>"syxdpH2UZaHvrzsmpJxBZA", "masqueraded_resource_class"=>"User", "id"=>"16203"}
  [1m[36mUser Load (0.6ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2[0m  [["id", 2], ["LIMIT", 1]]
  [1m[36mRoleshopuser Load (0.7ms)[0m  [1m[34mSELECT "roleshopusers".* FROM "roleshopusers" WHERE "roleshopusers"."user_id" = $1[0m  [["user_id", 2]]
  ↳ app/controllers/application_controller.rb:268:in `multiple_roles'
  [1m[36mUser Load (0.6ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 AND "users"."id" = $2 ORDER BY "users"."id" ASC LIMIT $3[0m  [["id", 16203], ["id", 16203], ["LIMIT", 1]]
Redirected to http://localhost:3000/
Completed 302 Found in 14ms (ActiveRecord: 1.8ms | Allocations: 5109)

Started GET "/" for ::1 at 2021-01-29 09:21:48 +0100
Processing by WelcomeController#home as HTML

```
and the view shown clearly indicates that one is masquerading:
![Screen Shot 2021-01-29 at 9 28 04](https://user-images.githubusercontent.com/716130/106250757-5cc1ba00-6214-11eb-9d51-c48ac4a7409f.png)

However, deploying to a VPS, going through the same steps, there is first a redirection to `Redirected to https://[domain]/users/sign_in` before getting the root_path.

```

Started GET "/users/masquerade/16203?masquerade=oyQZ7gRANUK4uNkB_cSB-A&masqueraded_resource_class=User" for 5.[...]52 at 2021-01-29 08:32:07 +0000
Cannot render console from 5.[...]52! Allowed networks: 127.0.0.0/127.255.255.255, ::1
Processing by Devise::MasqueradesController#show as HTML
  Parameters: {"masquerade"=>"oyQZ7gRANUK4uNkB_cSB-A", "masqueraded_resource_class"=>"User", "id"=>"16203"}
  ^[[1m^[[36mUser Load (0.4ms)^[[0m  ^[[1m^[[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2^[[0m  [["id", 2], ["LIMIT", 1]]
  ^[[1m^[[36mRoleshopuser Load (0.6ms)^[[0m  ^[[1m^[[34mSELECT "roleshopusers".* FROM "roleshopusers" WHERE "roleshopusers"."user_id" = $1^[[0m  [["user_id", 2]]
  ↳ app/controllers/application_controller.rb:268:in `multiple_roles'
  ^[[1m^[[36mUser Load (0.5ms)^[[0m  ^[[1m^[[34mSELECT "users".* FROM "users" WHERE "users"."id" IS NULL AND "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2^[[0m  [["id", 16203], ["LIMIT", 1]]
Redirected to https://[domain]/users/sign_in
Completed 302 Found in 11ms (ActiveRecord: 1.5ms | Allocations: 4800)


Started GET "/users/sign_in" for 5.[...]52 at 2021-01-29 08:32:07 +0000
Cannot render console from 5.[...]52! Allowed networks: 127.0.0.0/127.255.255.255, ::1
Processing by Devise::SessionsController#new as HTML
  ^[[1m^[[36mUser Load (0.4ms)^[[0m  ^[[1m^[[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2^[[0m  [["id", 2], ["LIMIT", 1]]
Redirected to https://[domain]/
Filter chain halted as :require_no_authentication rendered or redirected
Completed 302 Found in 5ms (ActiveRecord: 0.4ms | Allocations: 1922)


Started GET "/" for 5.[...]52 at 2021-01-29 08:32:07 +0000
Cannot render console from 5.[...]52! Allowed networks: 127.0.0.0/127.255.255.255, ::1
Processing by WelcomeController#home as HTML
```
Being already signed-in, the user is being re-set by devise and the masquerading is that of the admin user (id: 2), not the expected (id: 16203).  This was functioning as per gem design until recently *(I will attempt to dial back and find what change might have impacted this)*

a) is there a way to avoid devise detection?
b) how can the same code base be different between localhost and a VPS/url-driven request?

**Comment by sedubois** [comment]
How is this related to administrate?

**Comment by dvodvo** [comment]
Sorry, wrong gem.  `devise-masquerade` is the target.
