### ISSUE TITLE
source_reflection: undefined method `klass' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by dmc2015** [thoughtbot/administrate#1881]
* What were you trying to do?
 `rails generate administrate:install`
 
* What did you end up with (logs, or, even better, example apps are great!)?
Below

* What versions are you running?
  - Rails
  6.0.3
 - administrate
administrate (0.14.0)

#308 

```
user$ rails generate administrate:install
Running via Spring preloader in process 11683
       route  namespace :admin do
    resources :users
    resources :xxx
    resources :xxx
    resources :join_table

    root to: "users#index"
  end
WARNING: Unable to generate a dashboard for Delayed::Backend::ActiveRecord::Job.
       - Administrate does not yet support namespaced models.
      create  app/controllers/admin/application_controller.rb
      create  app/dashboards/user_dashboard.rb
      create  app/controllers/admin/users_controller.rb
      create  app/dashboards/join_dashboard.rb
      create  app/controllers/admin/joins_controller.rb
      create  app/dashboards/xxx_dashboard.rb
      create  app/controllers/admin/xxx_controller.rb
      create  app/dashboards/xxx_dashboard.rb
      create  app/controllers/admin/xxx_controller.rb
      create  app/dashboards/xxx_dashboard.rb
      create  app/controllers/admin/xxx_controller.rb
      create  app/dashboards/xxx_dashboard.rb
      create  app/controllers/admin/xxx_controller.rb
      create  app/dashboards/xxx_dashboard.rb
      create  app/controllers/admin/xxx_controller.rb
      create  app/dashboards/xxx_dashboard.rb
      create  app/controllers/admin/xxx_controller.rb
Traceback (most recent call last):
        73: from -e:1:in `<main>'
        72: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        71: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        70: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:318:in `load'
        69: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
        68: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:318:in `block in load'
        67: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
        66: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
        65: from /Users/user/dev/rails/app/bin/rails:9:in `<top (required)>'
        64: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'
        63: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
        62: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `block in require'
        61: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        60: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        59: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        58: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        57: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        56: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-6.0.3.4/lib/rails/commands.rb:18:in `<top (required)>'
        55: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-6.0.3.4/lib/rails/command.rb:46:in `invoke'
        54: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-6.0.3.4/lib/rails/command/base.rb:69:in `perform'
        53: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        52: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        51: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        50: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-6.0.3.4/lib/rails/commands/generate/generate_command.rb:26:in `perform'
        49: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-6.0.3.4/lib/rails/generators.rb:276:in `invoke'
        48: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
        47: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/group.rb:232:in `dispatch'
        46: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `invoke_all'
        45: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `map'
        44: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `each'
        43: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `block in invoke_all'
        42: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        41: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        40: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/administrate-0.14.0/lib/generators/administrate/install/install_generator.rb:28:in `run_dashboard_generators'
        39: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/administrate-0.14.0/lib/generators/administrate/install/install_generator.rb:28:in `each'
        38: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/administrate-0.14.0/lib/generators/administrate/install/install_generator.rb:29:in `block in run_dashboard_generators'
        37: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/administrate-0.14.0/lib/administrate/generator_helpers.rb:4:in `call_generator'
        36: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-6.0.3.4/lib/rails/generators.rb:276:in `invoke'
        35: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
        34: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/group.rb:232:in `dispatch'
        33: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `invoke_all'
        32: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `map'
        31: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `each'
        30: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `block in invoke_all'
        29: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        28: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        27: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/administrate-0.14.0/lib/generators/administrate/dashboard/dashboard_generator.rb:34:in `create_dashboard_definition'
        26: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-6.0.3.4/lib/rails/generators/named_base.rb:24:in `template'
        25: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-6.0.3.4/lib/rails/generators/named_base.rb:45:in `inside_template'
        24: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-6.0.3.4/lib/rails/generators/named_base.rb:25:in `block in template'
        23: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/actions/file_manipulation.rb:122:in `template'
        22: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/actions/create_file.rb:25:in `create_file'
        21: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/actions.rb:93:in `action'
        20: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/actions/create_file.rb:60:in `invoke!'
        19: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/actions/empty_directory.rb:117:in `invoke_with_conflict_check'
        18: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/actions/create_file.rb:63:in `block in invoke!'
        17: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/actions/create_file.rb:63:in `open'
        16: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/actions/create_file.rb:63:in `block (2 levels) in invoke!'
        15: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/actions/create_file.rb:53:in `render'
        14: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-1.0.1/lib/thor/actions/file_manipulation.rb:131:in `block in template'
        13: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/2.5.0/erb.rb:885:in `result'
        12: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/2.5.0/erb.rb:885:in `eval'
        11: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/administrate-0.14.0/lib/generators/administrate/dashboard/templates/dashboard.rb.erb:11:in `template'
        10: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/administrate-0.14.0/lib/generators/administrate/dashboard/dashboard_generator.rb:57:in `attributes'
         9: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/administrate-0.14.0/lib/generators/administrate/dashboard/dashboard_generator.rb:65:in `redundant_attributes'
         8: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/administrate-0.14.0/lib/generators/administrate/dashboard/dashboard_generator.rb:65:in `flat_map'
         7: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/administrate-0.14.0/lib/generators/administrate/dashboard/dashboard_generator.rb:65:in `each'
         6: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/administrate-0.14.0/lib/generators/administrate/dashboard/dashboard_generator.rb:66:in `block in redundant_attributes'
         5: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/administrate-0.14.0/lib/generators/administrate/dashboard/dashboard_generator.rb:71:in `redundant_attributes_for'
         4: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/administrate-0.14.0/lib/generators/administrate/dashboard/dashboard_generator.rb:112:in `association_type'
         3: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/administrate-0.14.0/lib/generators/administrate/dashboard/dashboard_generator.rb:125:in `relationship_options_string'
         2: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-6.0.3.4/lib/active_record/reflection.rb:166:in `class_name'
         1: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-6.0.3.4/lib/active_record/reflection.rb:989:in `derive_class_name'
/Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-6.0.3.4/lib/active_record/reflection.rb:790:in `source_reflection': undefined method `klass' for nil:NilClass (NoMethodError)
```

**Comment by pablobm** [comment]
Hello @dmc2015, thank you for your report. I've been tracing down the error you show, but I've hit a dead end. From the backtrace and the fact that you link issue #308, I gather you have a `through` relationship going. Can you show something about it? For example, is it "has_many through has_many", "has_many through belongs_to", etc?
