### ISSUE TITLE
"ActionView::Template::Error: Please use symbols for polymorphic route arguments" on Rails 6.1.3.2

### ISSUE THREAD

**Issue by blocknotes** [thoughtbot/administrate#1979]
The issue looks the same reported here: [ref issue](https://github.com/rails/rails/issues/42157).

---

* What were you trying to do?

Opening any admin route.

* What did you end up with (logs, or, even better, example apps are great!)?
```
2021-05-08 09:25:52 +0200: Rack app error handling request { GET /admin }
#<ActionView::Template::Error: Please use symbols for polymorphic route arguments.>
/Users/mat/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.1.3.2/lib/action_dispatch/routing/polymorphic_routes.rb:310:in `handle_list'
/Users/mat/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.1.3.2/lib/action_dispatch/routing/polymorphic_routes.rb:218:in `polymorphic_method'
/Users/mat/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.1.3.2/lib/action_dispatch/routing/polymorphic_routes.rb:139:in `polymorphic_path'
/Users/mat/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/actionview-6.1.3.2/lib/action_view/routing_url_for.rb:102:in `url_for'
/Users/mat/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/actionview-6.1.3.2/lib/action_view/helpers/url_helper.rb:202:in `link_to'
#...
```

I got the error from the CI initially and then tried locally, dummy app:
https://github.com/blocknotes/administrate_ransack/tree/master/spec/dummy
If you clone the repo and run `bin/rails s` (it's proxied by the dummy app).

* What versions are you running?
  - Rails: 6.1.3.2
  - administrate: 0.16

**Comment by efatsi** [comment]
Adding in here that the `namespace` method is returning a string for me, which throws a bomb in every administrate link. Adding this to my `Admin::ApplicationController` serves as a decent bandaid:

```ruby
def namespace
  super.to_sym
end
```
