### ISSUE TITLE
Could not find generator 'administrate:install'

### ISSUE THREAD

**Issue by Asandolo** [thoughtbot/administrate#2031]
I trying to `rails generate administrate:install`

*Log : 

```
Running via Spring preloader in process 22765
[WARNING] Could not load generator "generators/administrate/install/install_generator". Error: Support for calling #default_scope without a block is removed. For example instead of `default_scope where(color: 'red')`, please use `default_scope { where(color: 'red') }`. (Alternatively you can just redefine self.default_scope.).
/Users/asandolo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activerecord-6.1.4/lib/active_record/scoping/default.rb:92:in `default_scope'
/Users/asandolo/nivo/testadm/app/models/playlist_video.rb:2:in `<class:PlaylistVideo>'
/Users/asandolo/nivo/testadm/app/models/playlist_video.rb:1:in `<main>'
/Users/asandolo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/Users/asandolo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/Users/asandolo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/asandolo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/Users/asandolo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/Users/asandolo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:26:in `require'
/Users/asandolo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:409:in `const_get'
/Users/asandolo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:409:in `block (2 levels) in eager_load'
/Users/asandolo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:733:in `block in ls'
/Users/asandolo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:725:in `foreach'
/Users/asandolo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:725:in `ls'
/Users/asandolo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:404:in `block in eager_load'
/Users/asandolo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:393:in `synchronize'
/Users/asandolo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:393:in `eager_load'
/Users/asandolo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:508:in `each'
/Users/asandolo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:508:in `eager_load_all'
/Users/asandolo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/administrate-0.16.0/lib/generators/administrate/install/install_generator.rb:2:in `<main>'
/Users/asandolo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/Users/asandolo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/Users/asandolo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/asandolo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/Users/asandolo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/Users/asandolo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
/Users/asandolo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.1.4/lib/rails/command/behavior.rb:44:in `block (2 levels) in lookup'
/Users/asandolo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.1.4/lib/rails/command/behavior.rb:40:in `each'
/Users/asandolo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.1.4/lib/rails/command/behavior.rb:40:in `block in lookup'
/Users/asandolo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.1.4/lib/rails/command/behavior.rb:39:in `each'
/Users/asandolo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.1.4/lib/rails/command/behavior.rb:39:in `lookup'
/Users/asandolo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.1.4/lib/rails/generators.rb:257:in `find_by_namespace'
/Users/asandolo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.1.4/lib/rails/generators.rb:273:in `invoke'
/Users/asandolo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.1.4/lib/rails/commands/generate/generate_command.rb:26:in `perform'
/Users/asandolo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
/Users/asandolo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
/Users/asandolo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
/Users/asandolo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.1.4/lib/rails/command/base.rb:69:in `perform'
/Users/asandolo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.1.4/lib/rails/command.rb:48:in `invoke'
/Users/asandolo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.1.4/lib/rails/commands.rb:18:in `<main>'
/Users/asandolo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/Users/asandolo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/Users/asandolo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/asandolo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/Users/asandolo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/Users/asandolo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
/Users/asandolo/nivo/testadm/bin/rails:5:in `<main>'
/Users/asandolo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:60:in `load'
/Users/asandolo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:60:in `load'
/Users/asandolo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.4/lib/active_support/fork_tracker.rb:10:in `block in fork'
/Users/asandolo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.4/lib/active_support/fork_tracker.rb:8:in `fork'
/Users/asandolo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.4/lib/active_support/fork_tracker.rb:8:in `fork'
/Users/asandolo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.4/lib/active_support/fork_tracker.rb:27:in `fork'
/Users/asandolo/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
/Users/asandolo/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
-e:1:in `<main>'
Could not find generator 'administrate:install'. Maybe you meant "administrate:field"?
Run `bin/rails generate --help` for more options.

```
* Version: 
  - Rails `Rails 6.1.4`
  - administrate `0.16.0`

**Comment by maysam** [comment]
@Asandolo what was the solution?

**Comment by pablobm** [comment]
@maysam - Judging from their error message ("Error: Support for calling #default_scope without a block is removed"), I think that there was an error in their app, which caused Rails to fail while loading the generator.

**Comment by maysam** [comment]
@pablobm  I have the same version working in one project and not in the other, seems to be a side effect of something else, but cannot figure it out

**Comment by pablobm** [comment]
Do you have an exception message and trace that you can paste?

**Comment by maysam** [comment]
@pablobm 
```
 bundle exec rails g administrate:install
Running via Spring preloader in process 124224
[WARNING] Could not load generator "generators/administrate/install/install_generator". Error: uninitialized constant Mail::TestMailer

      delegate :deliveries, :deliveries=, to: Mail::TestMailer
                                                  ^^^^^^^^^^^^.
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/actionmailer-6.1.5/lib/action_mailer/delivery_methods.rb:42:in `<module:ClassMethods>'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/actionmailer-6.1.5/lib/action_mailer/delivery_methods.rb:40:in `<module:DeliveryMethods>'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/actionmailer-6.1.5/lib/action_mailer/delivery_methods.rb:8:in `<module:ActionMailer>'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/actionmailer-6.1.5/lib/action_mailer/delivery_methods.rb:5:in `<main>'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/actionmailer-6.1.5/lib/action_mailer/base.rb:438:in `<class:Base>'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/actionmailer-6.1.5/lib/action_mailer/base.rb:437:in `<module:ActionMailer>'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/actionmailer-6.1.5/lib/action_mailer/base.rb:12:in `<main>'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
/home/maysam/xxx/app/mailers/application_mailer.rb:3:in `<main>'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:27:in `require'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:95:in `const_get'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:95:in `cget'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:237:in `block (2 levels) in eager_load'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:26:in `block in ls'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:18:in `each_child'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:18:in `ls'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:232:in `block in eager_load'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:217:in `synchronize'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:217:in `eager_load'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:317:in `each'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:317:in `eager_load_all'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/administrate-0.17.0/lib/generators/administrate/install/install_generator.rb:2:in `<main>'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-6.1.5/lib/rails/command/behavior.rb:44:in `block (2 levels) in lookup'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-6.1.5/lib/rails/command/behavior.rb:40:in `each'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-6.1.5/lib/rails/command/behavior.rb:40:in `block in lookup'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-6.1.5/lib/rails/command/behavior.rb:39:in `each'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-6.1.5/lib/rails/command/behavior.rb:39:in `lookup'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-6.1.5/lib/rails/generators.rb:257:in `find_by_namespace'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-6.1.5/lib/rails/generators.rb:273:in `invoke'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-6.1.5/lib/rails/commands/generate/generate_command.rb:26:in `perform'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-6.1.5/lib/rails/command/base.rb:69:in `perform'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-6.1.5/lib/rails/command.rb:48:in `invoke'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/railties-6.1.5/lib/rails/commands.rb:18:in `<main>'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
/home/maysam/xxx/bin/rails:7:in `<main>'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/spring-4.0.0/lib/spring/commands/rails.rb:6:in `call'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/spring-4.0.0/lib/spring/command_wrapper.rb:38:in `call'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/spring-4.0.0/lib/spring/application.rb:217:in `block in serve'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-6.1.5/lib/active_support/fork_tracker.rb:10:in `block in fork'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-6.1.5/lib/active_support/fork_tracker.rb:10:in `block in fork'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-6.1.5/lib/active_support/fork_tracker.rb:8:in `fork'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-6.1.5/lib/active_support/fork_tracker.rb:8:in `fork'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-6.1.5/lib/active_support/fork_tracker.rb:27:in `fork'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-6.1.5/lib/active_support/fork_tracker.rb:8:in `fork'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activesupport-6.1.5/lib/active_support/fork_tracker.rb:27:in `fork'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/spring-4.0.0/lib/spring/application.rb:181:in `serve'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/spring-4.0.0/lib/spring/application.rb:144:in `block in run'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/spring-4.0.0/lib/spring/application.rb:138:in `loop'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/spring-4.0.0/lib/spring/application.rb:138:in `run'
/home/maysam/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/spring-4.0.0/lib/spring/application/boot.rb:19:in `<top (required)>'
<internal:/home/maysam/.rbenv/versions/3.1.1/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/home/maysam/.rbenv/versions/3.1.1/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
-e:1:in `<main>'
Could not find generator 'administrate:install'. Maybe you meant "administrate:views"?
```

**Comment by pablobm** [comment]
The problem appears to be with that `Mail::TestMailer`. For whatever reason it's not loaded (`require`-d) by the time `ApplicationMailer` is loaded, so the program crashes.

Do other generators (for example: controller generators) work in that app? I would assume that they fail too... Although I'm seeing that Administrate's generators do an explicit `Zeitwerk::Loader.eager_load_all` which appears in your expection trace (`/lib/generators/administrate/install/install_generator.rb:2`) and I have no idea of what whether it would cause problems.

I'm not very familiar with actionmailer lately. This `Mail::TestMailer` of yours: is it a module of yours? In which path does it live? It doesn't look to me like something that would live under `/app`. It may need an explicit `require` somewhere, perhaps an initializer.

**Comment by maysam** [comment]
Thanks @pablobm 
adding `gem 'net-smtp', require: false` to Gemfile solved the issue, help from https://stackoverflow.com/a/70500221/348701
