### ISSUE TITLE
uninitialized constant User::SharedAlbum (NameError)

### ISSUE THREAD

**Issue by fahidqbx** [thoughtbot/administrate#210]
I want to create admin dashboard which showing me this error.

I Configured devise in my App with 2 modules [admins, users]

I think that makes some issues but not sure.

```
rails g administrate:dashboard  User
/home/fahidnasir/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/inheritance.rb:158:in `compute_type': uninitialized constant User::SharedAlbum (NameError)
	from /home/fahidnasir/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/reflection.rb:271:in `compute_class'
	from /home/fahidnasir/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/reflection.rb:267:in `klass'
	from /home/fahidnasir/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/reflection.rb:661:in `source_reflection'
	from /home/fahidnasir/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/reflection.rb:871:in `derive_class_name'
	from /home/fahidnasir/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/reflection.rb:147:in `class_name'
	from /home/fahidnasir/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/administrate-0.0.12/lib/generators/administrate/dashboard/dashboard_generator.rb:85:in `relationship_options_string'
	from /home/fahidnasir/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/administrate-0.0.12/lib/generators/administrate/dashboard/dashboard_generator.rb:72:in `association_type'
	from /home/fahidnasir/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/administrate-0.0.12/lib/generators/administrate/dashboard/dashboard_generator.rb:48:in `redundant_attributes_for'
	from /home/fahidnasir/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/administrate-0.0.12/lib/generators/administrate/dashboard/dashboard_generator.rb:43:in `block in redundant_attributes'
	from /home/fahidnasir/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/administrate-0.0.12/lib/generators/administrate/dashboard/dashboard_generator.rb:42:in `each'
	from /home/fahidnasir/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/administrate-0.0.12/lib/generators/administrate/dashboard/dashboard_generator.rb:42:in `flat_map'
	from /home/fahidnasir/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/administrate-0.0.12/lib/generators/administrate/dashboard/dashboard_generator.rb:42:in `redundant_attributes'
	from /home/fahidnasir/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/administrate-0.0.12/lib/generators/administrate/dashboard/dashboard_generator.rb:38:in `attributes'
	from (erb):17:in `template'
	from /home/fahidnasir/.rbenv/versions/2.1.5/lib/ruby/2.1.0/erb.rb:850:in `eval'
	from /home/fahidnasir/.rbenv/versions/2.1.5/lib/ruby/2.1.0/erb.rb:850:in `result'
	from /home/fahidnasir/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/actions/file_manipulation.rb:116:in `block in template'
	from /home/fahidnasir/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:53:in `call'
	from /home/fahidnasir/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:53:in `render'
	from /home/fahidnasir/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:46:in `identical?'
	from /home/fahidnasir/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:72:in `on_conflict_behavior'
	from /home/fahidnasir/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/actions/empty_directory.rb:113:in `invoke_with_conflict_check'
	from /home/fahidnasir/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:60:in `invoke!'
	from /home/fahidnasir/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/actions.rb:94:in `action'
	from /home/fahidnasir/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:25:in `create_file'
	from /home/fahidnasir/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/actions/file_manipulation.rb:115:in `template'
	from /home/fahidnasir/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/generators/named_base.rb:26:in `block in template'
	from /home/fahidnasir/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/generators/named_base.rb:60:in `inside_template'
	from /home/fahidnasir/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/generators/named_base.rb:25:in `template'
	from /home/fahidnasir/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/administrate-0.0.12/lib/generators/administrate/dashboard/dashboard_generator.rb:25:in `create_dashboard_definition'
	from /home/fahidnasir/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /home/fahidnasir/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/fahidnasir/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /home/fahidnasir/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /home/fahidnasir/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /home/fahidnasir/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /home/fahidnasir/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /home/fahidnasir/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /home/fahidnasir/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/generators.rb:157:in `invoke'
	from /home/fahidnasir/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/commands/generate.rb:13:in `<top (required)>'
	from /home/fahidnasir/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /home/fahidnasir/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/fahidnasir/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/fahidnasir/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /home/fahidnasir/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
	from /home/fahidnasir/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:130:in `generate_or_destroy'
	from /home/fahidnasir/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:50:in `generate'
	from /home/fahidnasir/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/fahidnasir/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by fahidqbx** [comment]
it was fixed by refactoring the model's relationships.
Apologies for that.

**Comment by graysonwright** [comment]
@fahidqbx no problem!
