### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by johncblandii** [thoughtbot/administrate#219]
We're hitting a problem installing Administrate. Any ideas would be helpful.

Steps:
- Add to `Gemfile`
- `bundle`

The error below is the output. I noticed there is a file named `app/dashboards/#<class:0x007fcf52bfe248>_dashboard.rb` it creates.

`dashboard_manifest.rb` has the following dashboards:
```
  DASHBOARDS = [
    :#<class:0x007fcf52bfe248>s,
    :#<class:0x007fcf52d7c520>s,
    :#<class:0x007fcf567ea7e8>s,
    :#<class:0x007fcf52f1f1c0>s,
    :#<class:0x007fcf560eabf0>s,
    :#<class:0x007fcf565a0898>s,
    :#<class:0x007fcf520597f8>s,
    :#<class:0x007fcf56509ba0>s,
    :#<class:0x007fcf52cf6650>s,
    :#<class:0x007fcf56202808>s,
    :users,
    :churches,
    :locations,
    :roles,
    :users_roles,
    :members,
  ]
```

Error output:
```
$: rails generate administrate:install
      create  app/controllers/admin/application_controller.rb
      create  app/dashboards/dashboard_manifest.rb
       route  namespace :admin do
    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end

    root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
  end
      create  app/dashboards/#<class:0x007fcf52bfe248>_dashboard.rb
/Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/administrate-0.1.0/lib/generators/administrate/dashboard/dashboard_generator.rb:87:in `const_get': wrong constant name #<class:0x007fcf52bfe248> (NameError)
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/administrate-0.1.0/lib/generators/administrate/dashboard/dashboard_generator.rb:87:in `klass'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/administrate-0.1.0/lib/generators/administrate/dashboard/dashboard_generator.rb:40:in `attributes'
	from (erb):11:in `template'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/2.2.0/erb.rb:863:in `eval'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/2.2.0/erb.rb:863:in `result'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/file_manipulation.rb:116:in `block in template'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:53:in `call'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:53:in `render'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:62:in `block (2 levels) in invoke!'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:62:in `open'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:62:in `block in invoke!'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/empty_directory.rb:116:in `call'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/empty_directory.rb:116:in `invoke_with_conflict_check'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:60:in `invoke!'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions.rb:94:in `action'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:25:in `create_file'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/file_manipulation.rb:115:in `template'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/generators/named_base.rb:26:in `block in template'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/generators/named_base.rb:60:in `inside_template'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/generators/named_base.rb:25:in `template'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/administrate-0.1.0/lib/generators/administrate/dashboard/dashboard_generator.rb:27:in `create_dashboard_definition'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/generators.rb:157:in `invoke'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/administrate-0.1.0/lib/generators/administrate/install/install_generator.rb:29:in `block in run_dashboard_generators'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/administrate-0.1.0/lib/generators/administrate/install/install_generator.rb:28:in `each'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/administrate-0.1.0/lib/generators/administrate/install/install_generator.rb:28:in `run_dashboard_generators'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/generators.rb:157:in `invoke'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/commands/generate.rb:13:in `<top (required)>'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:130:in `generate_or_destroy'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:50:in `generate'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /Users/johncblandii/Work/myapp/bin/rails:8:in `<top (required)>'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'
```

**Comment by graysonwright** [comment]
@johncblandii it looks like the same error that @astamm78 is seeing in https://github.com/thoughtbot/administrate/issues/145. Can you post the contents of your `Gemfile` and `Gemfile.lock`?

Also, if this repo's source code is available somewhere, it would be great if I could take a look at it. Thanks!

**Comment by johncblandii** [comment]
I tried searching for another issue but didn't find one.

The repo is private on bitbucket. If that step is needed, I wouldn't mind.

Gemfile
```
source 'https://rubygems.org'

gem 'rails', '4.2.4'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'autoprefixer-rails', '~> 6.0'
gem 'font-awesome-sass', '~> 4.4'
gem 'bh', '~> 1.3.4'

gem 'devise', '~> 3.5.2'
gem 'devise_invitable'
gem 'rolify'
gem 'pundit'

gem 'refile', require: 'refile/rails'
gem 'refile-mini_magick'
gem 'refile-s3'

gem 'rollbar', '~> 2.4.0'
gem 'oj', '~> 2.12.14' # json parsing

gem 'administrate'

group :development, :test do
  gem 'meta_request' # support for Rails Panel in Google Chrome
  gem 'byebug'
  gem 'rspec-rails'
  gem 'guard-rspec', require: false
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'shoulda-matchers', require: false
  gem 'pry-rails'
  # gem 'pry-bloodline'
  gem 'pry-rescue'
  gem 'pry-stack_explorer'
  gem 'rubocop'
  gem 'guard-rubocop'
end

group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
end

group :test do
  gem 'capybara'
  gem 'webrat'
  gem 'database_cleaner'
  gem 'json_spec'
  gem 'codeclimate-test-reporter', require: nil
  gem 'selenium-webdriver'
  gem 'poltergeist'
  gem 'launchy'
  gem 'rspec-sidekiq'
  gem 'rspec-mocks'
  gem 'simplecov', require: false
  gem 'codeclimate-test-reporter', require: nil
end
```

Gemfile.lock
```
GEM
  remote: https://rubygems.org/
  specs:
    actionmailer (4.2.4)
      actionpack (= 4.2.4)
      actionview (= 4.2.4)
      activejob (= 4.2.4)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 1.0, >= 1.0.5)
    actionpack (4.2.4)
      actionview (= 4.2.4)
      activesupport (= 4.2.4)
      rack (~> 1.6)
      rack-test (~> 0.6.2)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (4.2.4)
      activesupport (= 4.2.4)
      builder (~> 3.1)
      erubis (~> 2.7.0)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    activejob (4.2.4)
      activesupport (= 4.2.4)
      globalid (>= 0.3.0)
    activemodel (4.2.4)
      activesupport (= 4.2.4)
      builder (~> 3.1)
    activerecord (4.2.4)
      activemodel (= 4.2.4)
      activesupport (= 4.2.4)
      arel (~> 6.0)
    activesupport (4.2.4)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    addressable (2.3.8)
    administrate (0.1.0)
      autoprefixer-rails (~> 6.0)
      datetime_picker_rails (~> 0.0.5)
      inline_svg (~> 0.6)
      kaminari (~> 0.16)
      momentjs-rails (~> 2.8)
      neat (~> 1.1)
      normalize-rails (~> 3.0)
      rails (~> 4.2)
      sass (~> 3.4)
      selectize-rails (~> 0.6)
    arel (6.0.3)
    ast (2.1.0)
    astrolabe (1.3.1)
      parser (~> 2.2)
    autoprefixer-rails (6.0.3)
      execjs
      json
    aws-sdk (2.1.33)
      aws-sdk-resources (= 2.1.33)
    aws-sdk-core (2.1.33)
      jmespath (~> 1.0)
    aws-sdk-resources (2.1.33)
      aws-sdk-core (= 2.1.33)
    bcrypt (3.1.10)
    bh (1.3.4)
      actionpack
      activesupport
    binding_of_caller (0.7.2)
      debug_inspector (>= 0.0.1)
    bourbon (4.2.6)
      sass (~> 3.4)
      thor (~> 0.19)
    builder (3.2.2)
    byebug (6.0.2)
    callsite (0.0.11)
    capybara (2.5.0)
      mime-types (>= 1.16)
      nokogiri (>= 1.3.3)
      rack (>= 1.0.0)
      rack-test (>= 0.5.4)
      xpath (~> 2.0)
    celluloid (0.17.2)
      celluloid-essentials
      celluloid-extras
      celluloid-fsm
      celluloid-pool
      celluloid-supervision
      timers (>= 4.1.1)
    celluloid-essentials (0.20.5)
      timers (>= 4.1.1)
    celluloid-extras (0.20.5)
      timers (>= 4.1.1)
    celluloid-fsm (0.20.5)
      timers (>= 4.1.1)
    celluloid-pool (0.20.5)
      timers (>= 4.1.1)
    celluloid-supervision (0.20.5)
      timers (>= 4.1.1)
    childprocess (0.5.7)
      ffi (~> 1.0, >= 1.0.11)
    cliver (0.3.2)
    codeclimate-test-reporter (0.4.8)
      simplecov (>= 0.7.1, < 1.0.0)
    coderay (1.1.0)
    coffee-rails (4.1.0)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.9.1.1)
    connection_pool (2.2.0)
    database_cleaner (1.5.1)
    datetime_picker_rails (0.0.5)
      momentjs-rails (>= 2.8.1)
    debug_inspector (0.0.2)
    devise (3.5.2)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 3.2.6, < 5)
      responders
      thread_safe (~> 0.1)
      warden (~> 1.2.3)
    devise_invitable (1.5.3)
      actionmailer (>= 3.2.6, < 5)
      devise (>= 3.2.0)
    diff-lcs (1.2.5)
    docile (1.1.5)
    domain_name (0.5.25)
      unf (>= 0.0.5, < 1.0.0)
    erubis (2.7.0)
    execjs (2.6.0)
    factory_girl (4.5.0)
      activesupport (>= 3.0.0)
    factory_girl_rails (4.5.0)
      factory_girl (~> 4.5.0)
      railties (>= 3.0.0)
    faker (1.5.0)
      i18n (~> 0.5)
    ffi (1.9.10)
    font-awesome-sass (4.4.0)
      sass (>= 3.2)
    formatador (0.2.5)
    git-version-bump (0.15.1)
    globalid (0.3.6)
      activesupport (>= 4.1.0)
    guard (2.13.0)
      formatador (>= 0.2.4)
      listen (>= 2.7, <= 4.0)
      lumberjack (~> 1.0)
      nenv (~> 0.1)
      notiffany (~> 0.0)
      pry (>= 0.9.12)
      shellany (~> 0.0)
      thor (>= 0.18.1)
    guard-compat (1.2.1)
    guard-rspec (4.6.4)
      guard (~> 2.1)
      guard-compat (~> 1.1)
      rspec (>= 2.99.0, < 4.0)
    guard-rubocop (1.2.0)
      guard (~> 2.0)
      rubocop (~> 0.20)
    hitimes (1.2.3)
    http-cookie (1.0.2)
      domain_name (~> 0.5)
    i18n (0.7.0)
    inline_svg (0.6.1)
      activesupport (>= 4.0.4)
      loofah (>= 2.0)
      nokogiri (~> 1.6)
    interception (0.5)
    jbuilder (2.3.2)
      activesupport (>= 3.0.0, < 5)
      multi_json (~> 1.2)
    jmespath (1.1.3)
    jquery-rails (4.0.5)
      rails-dom-testing (~> 1.0)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    json (1.8.3)
    json_spec (1.1.4)
      multi_json (~> 1.0)
      rspec (>= 2.0, < 4.0)
    kaminari (0.16.3)
      actionpack (>= 3.0.0)
      activesupport (>= 3.0.0)
    launchy (2.4.3)
      addressable (~> 2.3)
    listen (3.0.3)
      rb-fsevent (>= 0.9.3)
      rb-inotify (>= 0.9)
    loofah (2.0.3)
      nokogiri (>= 1.5.9)
    lumberjack (1.0.9)
    mail (2.6.3)
      mime-types (>= 1.16, < 3)
    meta_request (0.3.4)
      callsite (~> 0.0, >= 0.0.11)
      rack-contrib (~> 1.1)
      railties (>= 3.0.0, < 5.0.0)
    method_source (0.8.2)
    mime-types (2.6.2)
    mini_magick (4.3.6)
    mini_portile (0.6.2)
    minitest (5.8.2)
    momentjs-rails (2.10.6)
      railties (>= 3.1)
    multi_json (1.11.2)
    neat (1.7.2)
      bourbon (>= 4.0)
      sass (>= 3.3)
    nenv (0.2.0)
    netrc (0.10.3)
    nokogiri (1.6.6.2)
      mini_portile (~> 0.6.0)
    normalize-rails (3.0.3)
    notiffany (0.0.8)
      nenv (~> 0.1)
      shellany (~> 0.0)
    oj (2.12.14)
    orm_adapter (0.5.0)
    parser (2.2.3.0)
      ast (>= 1.1, < 3.0)
    pg (0.18.3)
    poltergeist (1.7.0)
      capybara (~> 2.1)
      cliver (~> 0.3.1)
      multi_json (~> 1.0)
      websocket-driver (>= 0.2.0)
    powerpack (0.1.1)
    pry (0.10.3)
      coderay (~> 1.1.0)
      method_source (~> 0.8.1)
      slop (~> 3.4)
    pry-rails (0.3.4)
      pry (>= 0.9.10)
    pry-rescue (1.4.2)
      interception (>= 0.5)
      pry
    pry-stack_explorer (0.4.9.2)
      binding_of_caller (>= 0.7)
      pry (>= 0.9.11)
    pundit (1.0.1)
      activesupport (>= 3.0.0)
    rack (1.6.4)
    rack-contrib (1.4.0)
      git-version-bump (~> 0.15)
      rack (~> 1.4)
    rack-protection (1.5.3)
      rack
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (4.2.4)
      actionmailer (= 4.2.4)
      actionpack (= 4.2.4)
      actionview (= 4.2.4)
      activejob (= 4.2.4)
      activemodel (= 4.2.4)
      activerecord (= 4.2.4)
      activesupport (= 4.2.4)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.2.4)
      sprockets-rails
    rails-deprecated_sanitizer (1.0.3)
      activesupport (>= 4.2.0.alpha)
    rails-dom-testing (1.0.7)
      activesupport (>= 4.2.0.beta, < 5.0)
      nokogiri (~> 1.6.0)
      rails-deprecated_sanitizer (>= 1.0.1)
    rails-html-sanitizer (1.0.2)
      loofah (~> 2.0)
    railties (4.2.4)
      actionpack (= 4.2.4)
      activesupport (= 4.2.4)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rainbow (2.0.0)
    rake (10.4.2)
    rb-fsevent (0.9.6)
    rb-inotify (0.9.5)
      ffi (>= 0.5.0)
    rdoc (4.2.0)
    redis (3.2.1)
    redis-namespace (1.5.2)
      redis (~> 3.0, >= 3.0.4)
    refile (0.6.1)
      mime-types
      rest-client (~> 1.8)
      sinatra (~> 1.4.5)
    refile-mini_magick (0.2.0)
      mini_magick (~> 4.0)
      refile (~> 0.5)
    refile-s3 (0.2.0)
      aws-sdk (~> 2.0)
      refile (~> 0.6.0)
    responders (2.1.0)
      railties (>= 4.2.0, < 5)
    rest-client (1.8.0)
      http-cookie (>= 1.0.2, < 2.0)
      mime-types (>= 1.16, < 3.0)
      netrc (~> 0.7)
    rolify (4.1.1)
    rollbar (2.4.0)
      multi_json
    rspec (3.3.0)
      rspec-core (~> 3.3.0)
      rspec-expectations (~> 3.3.0)
      rspec-mocks (~> 3.3.0)
    rspec-core (3.3.2)
      rspec-support (~> 3.3.0)
    rspec-expectations (3.3.1)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.3.0)
    rspec-mocks (3.3.2)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.3.0)
    rspec-rails (3.3.3)
      actionpack (>= 3.0, < 4.3)
      activesupport (>= 3.0, < 4.3)
      railties (>= 3.0, < 4.3)
      rspec-core (~> 3.3.0)
      rspec-expectations (~> 3.3.0)
      rspec-mocks (~> 3.3.0)
      rspec-support (~> 3.3.0)
    rspec-sidekiq (2.1.0)
      rspec (~> 3.0, >= 3.0.0)
      sidekiq (>= 2.4.0)
    rspec-support (3.3.0)
    rubocop (0.34.2)
      astrolabe (~> 1.3)
      parser (>= 2.2.2.5, < 3.0)
      powerpack (~> 0.1)
      rainbow (>= 1.99.1, < 3.0)
      ruby-progressbar (~> 1.4)
    ruby-progressbar (1.7.5)
    rubyzip (1.1.7)
    sass (3.4.19)
    sass-rails (5.0.4)
      railties (>= 4.0.0, < 5.0)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (>= 1.1, < 3)
    sdoc (0.4.1)
      json (~> 1.7, >= 1.7.7)
      rdoc (~> 4.0)
    selectize-rails (0.12.1)
    selenium-webdriver (2.48.1)
      childprocess (~> 0.5)
      multi_json (~> 1.0)
      rubyzip (~> 1.0)
      websocket (~> 1.0)
    shellany (0.0.1)
    shoulda-matchers (3.0.1)
      activesupport (>= 4.0.0)
    sidekiq (3.5.2)
      celluloid (~> 0.17.2)
      connection_pool (~> 2.2, >= 2.2.0)
      json (~> 1.0)
      redis (~> 3.2, >= 3.2.1)
      redis-namespace (~> 1.5, >= 1.5.2)
    simplecov (0.10.0)
      docile (~> 1.1.0)
      json (~> 1.8)
      simplecov-html (~> 0.10.0)
    simplecov-html (0.10.0)
    sinatra (1.4.6)
      rack (~> 1.4)
      rack-protection (~> 1.4)
      tilt (>= 1.3, < 3)
    slop (3.6.0)
    spring (1.4.0)
    sprockets (3.4.0)
      rack (> 1, < 3)
    sprockets-rails (2.3.3)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      sprockets (>= 2.8, < 4.0)
    thor (0.19.1)
    thread_safe (0.3.5)
    tilt (2.0.1)
    timers (4.1.1)
      hitimes
    turbolinks (2.5.3)
      coffee-rails
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uglifier (2.7.2)
      execjs (>= 0.3.0)
      json (>= 1.8.0)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.7.1)
    warden (1.2.3)
      rack (>= 1.0)
    web-console (2.2.1)
      activemodel (>= 4.0)
      binding_of_caller (>= 0.7.2)
      railties (>= 4.0)
      sprockets-rails (>= 2.0, < 4.0)
    webrat (0.7.3)
      nokogiri (>= 1.2.0)
      rack (>= 1.0)
      rack-test (>= 0.5.3)
    websocket (1.2.2)
    websocket-driver (0.6.2)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.2)
    xpath (2.0.0)
      nokogiri (~> 1.3)

PLATFORMS
  ruby

DEPENDENCIES
  administrate
  autoprefixer-rails (~> 6.0)
  bh (~> 1.3.4)
  byebug
  capybara
  codeclimate-test-reporter
  coffee-rails (~> 4.1.0)
  database_cleaner
  devise (~> 3.5.2)
  devise_invitable
  factory_girl_rails
  faker
  font-awesome-sass (~> 4.4)
  guard-rspec
  guard-rubocop
  jbuilder (~> 2.0)
  jquery-rails
  json_spec
  launchy
  meta_request
  oj (~> 2.12.14)
  pg
  poltergeist
  pry-rails
  pry-rescue
  pry-stack_explorer
  pundit
  rails (= 4.2.4)
  refile
  refile-mini_magick
  refile-s3
  rolify
  rollbar (~> 2.4.0)
  rspec-mocks
  rspec-rails
  rspec-sidekiq
  rubocop
  sass-rails (~> 5.0)
  sdoc (~> 0.4.0)
  selenium-webdriver
  shoulda-matchers
  simplecov
  spring
  turbolinks
  uglifier (>= 1.3.0)
  web-console (~> 2.0)
  webrat

BUNDLED WITH
   1.10.6
```

Descendants:
```
[5] pry(main)> ActiveRecord::Base.descendants
=> [#<Class:0x007fcf52bfe248> (call '#<Class:0x007fcf52bfe248>.connection' to establish a connection),
 #<Class:0x007fcf52d7c520> (call '#<Class:0x007fcf52d7c520>.connection' to establish a connection),
 #<Class:0x007fcf567ea7e8> (call '#<Class:0x007fcf567ea7e8>.connection' to establish a connection),
 #<Class:0x007fcf52f1f1c0> (call '#<Class:0x007fcf52f1f1c0>.connection' to establish a connection),
 #<Class:0x007fcf560eabf0> (call '#<Class:0x007fcf560eabf0>.connection' to establish a connection),
 #<Class:0x007fcf565a0898> (call '#<Class:0x007fcf565a0898>.connection' to establish a connection),
 #<Class:0x007fcf520597f8> (call '#<Class:0x007fcf520597f8>.connection' to establish a connection),
 #<Class:0x007fcf56509ba0> (call '#<Class:0x007fcf56509ba0>.connection' to establish a connection),
 #<Class:0x007fcf52cf6650> (call '#<Class:0x007fcf52cf6650>.connection' to establish a connection),
 #<Class:0x007fcf56202808> (call '#<Class:0x007fcf56202808>.connection' to establish a connection),
 #<Class:0x007fcf51161048> (call '#<Class:0x007fcf51161048>.connection' to establish a connection),
 User (call 'User.connection' to establish a connection),
 User::HABTM_Roles (call 'User::HABTM_Roles.connection' to establish a connection)]

[6] pry(main)> ActiveRecord::Base.descendants.map(&:table_name)
=> ["users_roles",
 "users_roles",
 "users_roles",
 "users_roles",
 "users_roles",
 "users_roles",
 "users_roles",
 "users_roles",
 "users_roles",
 "users_roles",
 "users_roles",
 "users",
 "users_roles"]
```

**Comment by graysonwright** [comment]
Great. It'll probably be a little while before I can get to this, but I think #124 might take care of this problem. If you like, point your Gemfile to the master branch on github and try the installers from there.

```ruby
gem "administrate", github: "thoughtbot/administrate"
```

**Comment by johncblandii** [comment]
Same error using master.

**Comment by graysonwright** [comment]
interesting. Can you do a couple things for me in your rails console?

- `ActiveRecord::Base.descendants`
- `ActiveRecord::Base.descendants.map(&:table_name)`

**Comment by johncblandii** [comment]
See above.

**Comment by graysonwright** [comment]
oh, thanks! I missed that. (=

**Comment by johncblandii** [comment]
No prob. :)

**Comment by johncblandii** [comment]
How's this looking?

**Comment by graysonwright** [comment]
Good question! I finally have time to take a look at it today. :smile: 
I'll let you know when I find something.

**Comment by graysonwright** [comment]
@johncblandii can you do a search through your project for `has_and_belongs_to_many` and paste the results? Thanks!

**Comment by graysonwright** [comment]
Should be fixed by https://github.com/thoughtbot/administrate/pull/259 !

**Comment by johncblandii** [comment]
Awesome! I was away so didn't get to send the last details. We'll test this out.

**Comment by johncblandii** [comment]
FYI @warrenbrown. Test this out again.

**Comment by johncblandii** [comment]
Really late, but I tried this again yesterday and it worked. It's a pretty solid system. Thanks.

**Comment by MincePie** [comment]
How did you fix this. I can't follow what the solution to this problem is.
