### ISSUE TITLE
Exception: ActionView::Template::Error: uninitialized constant for multi-word model dashboard with irregular inflection

### ISSUE THREAD

**Issue by blainejohnson17** [thoughtbot/administrate#2409]
* What were you trying to do?
Setup admin dashboard for model with multi-word irregular inflection.
example: 
I have a dashboard class: `class MerchantBonusDashboard < Administrate::BaseDashboard`
And inflector: 
```
ActiveSupport::Inflector.inflections(:en) do |inflect|
  inflect.irregular 'merchant_bonus', 'merchant_bonuses'
end
```
during render of the dashboard I get error: 
```
Rails -- Exception: ActionView::Template::Error: uninitialized constant MerchantBonu
Did you mean?  MerchantBonus
```
Relevant part of the stack strace:
```
activesupport (6.1.7.4) lib/active_support/inflector/methods.rb:273:in `const_get'
activesupport (6.1.7.4) lib/active_support/inflector/methods.rb:273:in `constantize'
activesupport (6.1.7.4) lib/active_support/core_ext/string/inflections.rb:74:in `constantize'
administrate (0.19.0) lib/administrate/base_dashboard.rb:25:in `model'
activesupport (6.1.7.4) lib/active_support/core_ext/object/try.rb:15:in `public_send'
activesupport (6.1.7.4) lib/active_support/core_ext/object/try.rb:15:in `try'
administrate (0.19.0) app/helpers/administrate/application_helper.rb:26:in `model_from_resource' 
```
Looking at `lib/administrate/base_dashboard.rb:25:in `model'` 
I see this impl:
```
      def model
        to_s.chomp(DASHBOARD_SUFFIX).classify.constantize
      end
```
`to_s.chomp(DASHBOARD_SUFFIX)` =>`'MerchantBonus'`
`.classify` => `'MerchantBonu'`

Rails ActiveSupport Inflector method `classify` expects a underscore (snake_case) table name, but here we are giving it a CamelCase model name. classify does incidentally work when the `table_name` arg doesn't have an multi-word irregular inflection.

Seems like we should do an `underscore` operation on the CamelCase model name before classifying. e.g.
```
      def model
        to_s.chomp(DASHBOARD_SUFFIX).underscore.classify.constantize
      end
```
I _could_ also define an additional inflector for the CamelCase version `inflect.irregular 'MerchantBonus', 'MerchantBonuses'`. But that seems more of a hack that the proposed change above.

Happy to submit a PR if this seems like a reasonable fix or maybe I'm misunderstanding some aspect.

* What versions are you running?
  - Rails - (6.1.7.4)
  - administrate - (0.19.0)

**Comment by pablobm** [comment]
Your proposal sounds good to me. Go for it!

And thank you for looking into this :slightly_smiling_face:
