### ISSUE TITLE
Flakey spec: Search admin search with a filter with arguments

### ISSUE THREAD

**Issue by nickcharlton** [thoughtbot/administrate#2523]
Flakey, but consistently flakey since we merged in #2448.

```
Failures:

  1) Search admin searches with a filter with arguments
     Failure/Error: expect(page).not_to have_content(standard_match.email)
       expected not to find text "me@kind.com" in "Back to app\nCustomers\nLog Entries\nOrders\nPages\nProducts\nProduct Meta Tags\nPayments\nSeries\nBlog Posts\nBlog Tags\nStats\nCustomers\nYou are logged in as Admin.\nNew customer\nEmail Email Subscriber Lifetime Value Name Orders Log Entries Kind Territory Password\nvip@kind.com - $0.00 Customer 157 0 orders 0 log entries vip Country 201 Edit\nBecome\nme@kind.com - $0.00 Customer 158 0 orders 0 log entries standard Country 202 Edit\nBecome\nstandard@kind.com - $0.00 Customer 159 0 orders 0 log entries vip Country 203 Edit\nBecome"
     # ./spec/features/search_spec.rb:105:in `block (2 levels) in <top (required)>'
     # /Users/nickcharlton/.gem/ruby/3.2.2/gems/webmock-3.20.0/lib/webmock/rspec.rb:39:in `block (2 levels) in <top (required)>'

Finished in 14.98 seconds (files took 2.49 seconds to load)
579 examples, 1 failure

Failed examples:

rspec ./spec/features/search_spec.rb:88 # Search admin searches with a filter with arguments

Randomized with seed 33089
```

**Comment by mike-burns** [comment]
https://stackoverflow.com/questions/11980109/cucumber-capybara-check-that-a-page-does-not-have-content#comment134688856_35640662

I wonder (also don't have time to work on this right now), what if we swapped lines 106 and 105. Would that cause Capybara to wait correctly?
