### ISSUE TITLE
undefined method `display_resource_name' for...

### ISSUE THREAD

**Issue by akrisanov** [thoughtbot/administrate#355]
Hello,
just updated Administrate from 0.1.1. to 0.1.2 and got an exception:

```
ActionView::Template::Error (undefined method `display_resource_name' for #<#<Class:0x007f963510d2b8>:0x007f963503ed28>):
    22: %>
    23:
    24: <% content_for(:title) do %>
    25:   <%= display_resource_name(page.resource_name) %>
    26: <% end %>
    27:
    28: <% content_for(:search) do %>
  administrate (0.1.2) app/views/administrate/application/index.html.erb:25:in `block in ___sers_akrisanov__rvm_gems_ruby_______ridewithlocal_gems_administrate_______app_views_administrate_application_index_html_erb___3115278608800694785_70141529381000'
  actionview (4.2.5) lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
  actionview (4.2.5) lib/action_view/helpers/capture_helper.rb:202:in `with_output_buffer'
  actionview (4.2.5) lib/action_view/helpers/capture_helper.rb:38:in `capture'
  actionview (4.2.5) lib/action_view/helpers/capture_helper.rb:152:in `content_for'
  administrate (0.1.2) app/views/administrate/application/index.html.erb:24:in `___sers_akrisanov__rvm_gems_ruby_______ridewithlocal_gems_administrate_______app_views_administrate_application_index_html_erb___3115278608800694785_70141529381000'
  actionview (4.2.5) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.2.5) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.5) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.5) lib/active_support/notifications.rb:164:in `instrument'
  actionview (4.2.5) lib/action_view/template.rb:333:in `instrument'
  actionview (4.2.5) lib/action_view/template.rb:143:in `render'
  actionview (4.2.5) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
  actionview (4.2.5) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
  activesupport (4.2.5) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.5) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.5) lib/active_support/notifications.rb:164:in `instrument'
  actionview (4.2.5) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
  actionview (4.2.5) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
  actionview (4.2.5) lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
  actionview (4.2.5) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
  actionview (4.2.5) lib/action_view/renderer/template_renderer.rb:14:in `render'
  actionview (4.2.5) lib/action_view/renderer/renderer.rb:42:in `render_template'
  actionview (4.2.5) lib/action_view/renderer/renderer.rb:23:in `render'
  actionview (4.2.5) lib/action_view/rendering.rb:100:in `_render_template'
  actionpack (4.2.5) lib/action_controller/metal/streaming.rb:217:in `_render_template'
  actionview (4.2.5) lib/action_view/rendering.rb:83:in `render_to_body'
  actionpack (4.2.5) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
  actionpack (4.2.5) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
  actionpack (4.2.5) lib/abstract_controller/rendering.rb:25:in `render'
  actionpack (4.2.5) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (4.2.5) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
  activesupport (4.2.5) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /Users/akrisanov/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
  activesupport (4.2.5) lib/active_support/core_ext/benchmark.rb:12:in `ms'
  actionpack (4.2.5) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
  actionpack (4.2.5) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
  activerecord (4.2.5) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  actionpack (4.2.5) lib/action_controller/metal/instrumentation.rb:43:in `render'
  wicked_pdf (1.0.3) lib/wicked_pdf/pdf_helper.rb:23:in `render_with_wicked_pdf'
  remotipart (1.2.1) lib/remotipart/render_overrides.rb:14:in `render_with_remotipart'
  administrate (0.1.2) app/controllers/administrate/application_controller.rb:10:in `index'
  actionpack (4.2.5) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.5) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.5) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.5) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.5) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.5) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.5) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.5) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.5) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.5) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  activesupport (4.2.5) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  activesupport (4.2.5) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.5) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.5) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.5) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.5) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.5) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.5) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.5) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.5) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.5) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.5) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.5) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.5) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.5) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.5) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.5) lib/action_dispatch/routing/route_set.rb:76:in `call'
  actionpack (4.2.5) lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
  actionpack (4.2.5) lib/action_dispatch/routing/route_set.rb:45:in `serve'
  actionpack (4.2.5) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.5) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.5) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.5) lib/action_dispatch/routing/route_set.rb:817:in `call'
  ...
```

**Comment by zamith** [comment]
That method should be there, it might be something else you've done or overwrote.

Can you go to your console (`bundle exec rails console`) and run `Administrate::ApplicationHelper.instance_methods(false)`? What's the output of that?

You should be seeing this: `[:render_field, :display_resource_name]`

**Comment by akrisanov** [comment]
@zamith I see this:
```
2.2.3 (main):0 > Administrate::ApplicationHelper.instance_methods(false)
=> [
  [0] :render_field,
  [1] :diff
]
```

**Comment by zamith** [comment]
Right, so `display_resource_name` is really missing, but it shouldn't. Is you app code online and public?

**Comment by akrisanov** [comment]
**fields/history_field.rb**:
```
require 'administrate/fields/base'

class HistoryField < Administrate::Field::Base
  def to_s
    data
  end
end
```

**fields/history_field/_show.html.erb**:
```
<div class='row mt'>
  <div class='col-sm-12'>
    <h4><%= "Diff between Version #{resource.id} and Current Version" %></h2>
    <style><%= Diffy::CSS %></style>
    <p>
      <%= "Version on #{resource.created_at} by '#{resource.event.humanize}'." %>
    </p>
    <div class='well diff'>
      <% record = resource.reify %>
      <%= render 'fields/history_field/offer', resource: resource, record: record %>
    </div>
  </div>
</div>
```
**fields/history_field/_offer.html.erb**:
```
<% offer = Offer.find_by(id: resource.item_id) %>
<% if offer %>
  <p>
    <strong>Description:</strong>
    <%= diff(record.description, offer.description) %>
  </p>
<% end %>
```

**Comment by zamith** [comment]
Do you have the code where you defined your helper? It would be easier if the entire repo was public, so I could debug in my machine, but I understand if that is not a possibility.

**Comment by akrisanov** [comment]
@zamith thanks for `Administrate::ApplicationHelper.instance_methods(false)`. It's very useful.
I've figured out what the problem was. I overrode `ApplicationHelper` but I forgot to upgrade it for 0.1.2 :anguished:

**Comment by zamith** [comment]
@akrisanov Ha! That makes sense. Glad that you were able to fix it. ;)
