### ISSUE TITLE
Error undefined method `reflections' for Admin:Module (NoMethodError)

### ISSUE THREAD

**Issue by prem-prakash** [thoughtbot/administrate#487]
Getting this errors running rails generate administrate:install

```
% rails generate administrate:install                                                                                           1 ↵ ✖ ✹ ✭
   identical  app/controllers/admin/application_controller.rb
/Users/premprakash/.rvm/gems/ruby-2.2.3/gems/administrate-0.1.4/lib/generators/administrate/dashboard/dashboard_generator.rb:47:in `attributes': undefined method `reflections' for Admin:Module (NoMethodError)
	from (erb):11:in `template'
	from /Users/premprakash/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/erb.rb:863:in `eval'
	from /Users/premprakash/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/erb.rb:863:in `result'
	from /Users/premprakash/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/actions/file_manipulation.rb:116:in `block in template'
	from /Users/premprakash/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/actions/create_file.rb:53:in `call'
	from /Users/premprakash/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/actions/create_file.rb:53:in `render'
	from /Users/premprakash/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/actions/create_file.rb:46:in `identical?'
	from /Users/premprakash/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/actions/create_file.rb:72:in `on_conflict_behavior'
	from /Users/premprakash/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/actions/empty_directory.rb:113:in `invoke_with_conflict_check'
	from /Users/premprakash/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/actions/create_file.rb:60:in `invoke!'
	from /Users/premprakash/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/actions.rb:94:in `action'
	from /Users/premprakash/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/actions/create_file.rb:25:in `create_file'
	from /Users/premprakash/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/actions/file_manipulation.rb:115:in `template'
	from /Users/premprakash/.rvm/gems/ruby-2.2.3/gems/railties-4.2.5/lib/rails/generators/named_base.rb:26:in `block in template'
	from /Users/premprakash/.rvm/gems/ruby-2.2.3/gems/railties-4.2.5/lib/rails/generators/named_base.rb:60:in `inside_template'
	from /Users/premprakash/.rvm/gems/ruby-2.2.3/gems/railties-4.2.5/lib/rails/generators/named_base.rb:25:in `template'
	from /Users/premprakash/.rvm/gems/ruby-2.2.3/gems/administrate-0.1.4/lib/generators/administrate/dashboard/dashboard_generator.rb:30:in `create_dashboard_definition'
	from /Users/premprakash/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/premprakash/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/premprakash/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /Users/premprakash/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /Users/premprakash/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /Users/premprakash/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /Users/premprakash/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /Users/premprakash/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/premprakash/.rvm/gems/ruby-2.2.3/gems/railties-4.2.5/lib/rails/generators.rb:157:in `invoke'
	from /Users/premprakash/.rvm/gems/ruby-2.2.3/gems/administrate-0.1.4/lib/administrate/generator_helpers.rb:4:in `call_generator'
	from /Users/premprakash/.rvm/gems/ruby-2.2.3/gems/administrate-0.1.4/lib/generators/administrate/install/install_generator.rb:27:in `block in run_dashboard_generators'
	from /Users/premprakash/.rvm/gems/ruby-2.2.3/gems/administrate-0.1.4/lib/generators/administrate/install/install_generator.rb:26:in `each'
	from /Users/premprakash/.rvm/gems/ruby-2.2.3/gems/administrate-0.1.4/lib/generators/administrate/install/install_generator.rb:26:in `run_dashboard_generators'
	from /Users/premprakash/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/premprakash/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/premprakash/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /Users/premprakash/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /Users/premprakash/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /Users/premprakash/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /Users/premprakash/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /Users/premprakash/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/premprakash/.rvm/gems/ruby-2.2.3/gems/railties-4.2.5/lib/rails/generators.rb:157:in `invoke'
	from /Users/premprakash/.rvm/gems/ruby-2.2.3/gems/railties-4.2.5/lib/rails/commands/generate.rb:13:in `<top (required)>'
	from /Users/premprakash/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /Users/premprakash/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/premprakash/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/premprakash/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /Users/premprakash/.rvm/gems/ruby-2.2.3/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
	from /Users/premprakash/.rvm/gems/ruby-2.2.3/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:130:in `generate_or_destroy'
	from /Users/premprakash/.rvm/gems/ruby-2.2.3/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:50:in `generate'
	from /Users/premprakash/.rvm/gems/ruby-2.2.3/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/premprakash/.rvm/gems/ruby-2.2.3/gems/railties-4.2.5/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/premprakash/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /Users/premprakash/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/premprakash/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/premprakash/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /Users/premprakash/Projects/escolademisterios/floresta/bin/rails:8:in `<top (required)>'
	from /Users/premprakash/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
	from /Users/premprakash/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/premprakash/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/premprakash/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
	from /Users/premprakash/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/premprakash/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'
```

My models:

```ruby
class Course < ActiveRecord::Base
  has_many :questions, through: :question_sets
  has_and_belongs_to_many :hymnbooks
  has_many :question_sets, dependent: :destroy, inverse_of: :course
  has_many :enrollment_periods, dependent: :destroy, inverse_of: :course

  scope :for_student, lambda { |student|
    joins(enrollment_periods: { group: :school })
      .where(groups: { school_id: student.school_id, student_status: Student.statuses[student.status] })
  }

  scope :opened, lambda {
    joins(:enrollment_periods).where(
      'enrollment_periods.starts_at < :now AND :now < enrollment_periods.ends_at',
      now: Time.current)
  }

  def to_param
    "#{id}-#{title.parameterize}"
  end
end

class EnrollmentPeriod < ActiveRecord::Base
  belongs_to :group
  belongs_to :course

  scope :for_student, lambda { |student|
    joins(group: :school)
      .where(groups: { school_id: student.school_id, student_status: Student.statuses[student.status] })
  }

  validates :course, :group, presence: true
end

class Group < ActiveRecord::Base
  belongs_to :school

  enum student_status: Student.statuses.symbolize_keys
end

class Option < ActiveRecord::Base
  belongs_to :question, inverse_of: :options
end

class Page < ActiveRecord::Base
  default_scope { order(:position) }

  def to_param
    "#{id}-#{title.parameterize}"
  end
end

class ParticipationRequest < ActiveRecord::Base
  belongs_to :student
end

class QuestionSet < ActiveRecord::Base
  belongs_to :question
  belongs_to :course, inverse_of: :question_sets

  default_scope { order(:position) }

  validates :question, :school, presence: true
end

class Question < ActiveRecord::Base
  has_many :options, inverse_of: :question
  has_many :question_sets
end

class School < ActiveRecord::Base
  has_many :students, inverse_of: :school
  has_one :group
end

class SelectedOption < ActiveRecord::Base
  belongs_to :subscription
  belongs_to :option
  belongs_to :question

  scope :sorted, -> { joins(question: :question_sets).order('question_sets.position') }

  def self.find_or_build(subscription)
    selected_options = []
    subscription.course.question_sets.order(:position).each do |question_set|
      selected_options << find_or_initialize_by(question: question_set.question)
    end
    selected_options
  end
end

class Student < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :timeoutable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :school, inverse_of: :students

  enum status: { active: 1, inactive: 0 }
end

class Subscription < ActiveRecord::Base
  belongs_to :student
  belongs_to :course
  has_many :selected_options, dependent: :destroy
  accepts_nested_attributes_for :selected_options

  validates :student, :course, presence: true

  enum status: { confirmed: 0, cancelled: 1, nonparticipating: 2 }

  def clean_options
    selected_options.update_all option_id: nil
  end

  def update_options(selected_options)
    update selected_options
  end

  def self.find_or_build(course, student)
    find_or_initialize_by(student: student, course: course)
  end
end

class VisitorProfile < ActiveRecord::Base
  belongs_to :student
end

```

**Comment by prem-prakash** [comment]
Solved by removing existing route

```ruby
  scope '/admin' do
    get '/credentials', to: 'admin#upload_credentials'
  end
```

**Comment by graysonwright** [comment]
@prem-prakash, glad you worked it out! I'll look at adding a better error message for the generator.
