### ISSUE TITLE
No such file to load -- administrate/fields/base 

### ISSUE THREAD

**Issue by BillyParadise** [thoughtbot/administrate#488]
After upgrading to 0.1.3 I am unable to deploy
```
INFO [7e8ef753] Running ~/.rvm/bin/rvm default do bundle exec bin/delayed_job -n 1 restart as x@x
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as x@x: bundle exit status: 1
bundle stdout: Nothing written
bundle stderr: /x/site/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `require': No such file to load -- administrate/fields/base (LoadError)
	from /x/site/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /x/site/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /x/site/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `require'
	from /x/site/releases/20160228052458/app/fields/enum_field.rb:1:in `<top (required)>'
```

cap production deploy:rollback to the rescue!

**Comment by BillyParadise** [comment]
This was created by issue #150  Please ignore.
