### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by sayshay** [thoughtbot/administrate#527]
```
source 'https://rubygems.org'

#ruby '2.1.2'

gem 'therubyracer'
gem 'less-rails'
gem 'twitter-bootstrap-rails'

gem 'rails', '4.2.0'
gem 'pg'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'bcrypt-ruby', '3.1.2'
gem 'omniauth'
gem 'omniauth-google-oauth2'
gem 'omniauth-facebook'
gem 'devise'
gem 'paperclip', '~> 4.3.1'
gem 'aws-sdk', '< 2.0'
gem 'geocoder'
gem 'area'
gem 'private_pub'
gem 'puma', '~> 2.15', '>= 2.15.3'
gem 'newrelic_rpm'
gem 'activeadmin', '~> 1.0.0.pre1'
gem 'jbuilder', '~> 2.0'
gem 'formtastic', '3.1.3'
gem 'skrollr-rails'
gem 'resque'
gem 'stripe'
gem 'figaro'
gem 'gmaps4rails'
gem 'cocoon'
gem 'mechanize'
gem 'paranoia', '~> 2.0'
gem 'amoeba'
gem 'edmunds_ruby', git: 'https://github.com/ronaldchacon/edmunds_ruby.git'
gem 'simple_token_authentication', '~> 1.8.0'
gem 'friendly_id', '~> 5.1'
gem 'delayed_job_active_record'
gem 'sass-rails'
gem 'google-api-client', '~> 0.7.1'
gem 'rollbar', '~> 2.8.1'
gem 'administrate'

group :development do
  gem 'better_errors'
  gem 'quiet_assets'
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'letter_opener'
  gem 'faker', '~> 1.5.0'
  gem 'binding_of_caller'
  gem 'sitemap_generator'
end

group :development, :test do
  gem 'factory_girl_rails'
  gem 'rspec-rails', '~> 3.0.0'
  gem 'capybara'
  gem 'zip-zip'
  gem 'selenium-webdriver'
  gem 'shoulda-matchers'
  gem 'database_cleaner'
  gem 'ruby-prof'
end

group :production do
  gem "memcachier"
  gem 'rails_12factor'
  # gem 'rack-timeout', '~> 0.3.2'
end

```

terminal:

```
rails generate administrate:install
      create  app/controllers/admin/application_controller.rb
      create  app/dashboards/dashboard_dashboard.rb
/Users/apprentice/.rvm/gems/ruby-2.2.2/gems/administrate-0.1.4/lib/generators/administrate/dashboard/dashboard_generator.rb:107:in `const_get': uninitialized constant Dashboard (NameError)
    from /Users/apprentice/.rvm/gems/ruby-2.2.2/gems/administrate-0.1.4/lib/generators/administrate/dashboard/dashboard_generator.rb:107:in `klass'
    from /Users/apprentice/.rvm/gems/ruby-2.2.2/gems/administrate-0.1.4/lib/generators/administrate/dashboard/dashboard_generator.rb:47:in `attributes'
    from (erb):11:in `template'
    from /Users/apprentice/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/erb.rb:863:in `eval'
    from /Users/apprentice/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/erb.rb:863:in `result'
    from /Users/apprentice/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/actions/file_manipulation.rb:116:in `block in template'
    from /Users/apprentice/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/actions/create_file.rb:53:in `call'
    from /Users/apprentice/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/actions/create_file.rb:53:in `render'
    from /Users/apprentice/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/actions/create_file.rb:62:in `block (2 levels) in invoke!'
    from /Users/apprentice/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/actions/create_file.rb:62:in `open'
    from /Users/apprentice/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/actions/create_file.rb:62:in `block in invoke!'
    from /Users/apprentice/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/actions/empty_directory.rb:116:in `call'
    from /Users/apprentice/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/actions/empty_directory.rb:116:in `invoke_with_conflict_check'
    from /Users/apprentice/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/actions/create_file.rb:60:in `invoke!'
    from /Users/apprentice/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/actions.rb:94:in `action'
    from /Users/apprentice/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/actions/create_file.rb:25:in `create_file'
    from /Users/apprentice/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/actions/file_manipulation.rb:115:in `template'
    from /Users/apprentice/.rvm/gems/ruby-2.2.2/gems/railties-4.2.0/lib/rails/generators/named_base.rb:26:in `block in template'
    from /Users/apprentice/.rvm/gems/ruby-2.2.2/gems/railties-4.2.0/lib/rails/generators/named_base.rb:60:in `inside_template'
    from /Users/apprentice/.rvm/gems/ruby-2.2.2/gems/railties-4.2.0/lib/rails/generators/named_base.rb:25:in `template'
    from /Users/apprentice/.rvm/gems/ruby-2.2.2/gems/administrate-0.1.4/lib/generators/administrate/dashboard/dashboard_generator.rb:30:in `create_dashboard_definition'
    from /Users/apprentice/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Users/apprentice/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Users/apprentice/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
    from /Users/apprentice/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
    from /Users/apprentice/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
    from /Users/apprentice/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
    from /Users/apprentice/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
    from /Users/apprentice/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /Users/apprentice/.rvm/gems/ruby-2.2.2/gems/railties-4.2.0/lib/rails/generators.rb:157:in `invoke'
    from /Users/apprentice/.rvm/gems/ruby-2.2.2/gems/administrate-0.1.4/lib/administrate/generator_helpers.rb:4:in `call_generator'
    from /Users/apprentice/.rvm/gems/ruby-2.2.2/gems/administrate-0.1.4/lib/generators/administrate/install/install_generator.rb:27:in `block in run_dashboard_generators'
    from /Users/apprentice/.rvm/gems/ruby-2.2.2/gems/administrate-0.1.4/lib/generators/administrate/install/install_generator.rb:26:in `each'
    from /Users/apprentice/.rvm/gems/ruby-2.2.2/gems/administrate-0.1.4/lib/generators/administrate/install/install_generator.rb:26:in `run_dashboard_generators'
    from /Users/apprentice/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Users/apprentice/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Users/apprentice/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
    from /Users/apprentice/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
    from /Users/apprentice/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
    from /Users/apprentice/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
    from /Users/apprentice/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
    from /Users/apprentice/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /Users/apprentice/.rvm/gems/ruby-2.2.2/gems/railties-4.2.0/lib/rails/generators.rb:157:in `invoke'
    from /Users/apprentice/.rvm/gems/ruby-2.2.2/gems/railties-4.2.0/lib/rails/commands/generate.rb:13:in `<top (required)>'
    from /Users/apprentice/.rvm/gems/ruby-2.2.2/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
    from /Users/apprentice/.rvm/gems/ruby-2.2.2/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:130:in `generate_or_destroy'
    from /Users/apprentice/.rvm/gems/ruby-2.2.2/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:50:in `generate'
    from /Users/apprentice/.rvm/gems/ruby-2.2.2/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
    from /Users/apprentice/.rvm/gems/ruby-2.2.2/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
    from bin/rails:8:in `require'
    from bin/rails:8:in `<main>'

```

**Comment by danielyewright** [comment]
I'm also receiving an install error:

```
~/Workspace/rails/sample_app $ rails generate administrate:install
Running via Spring preloader in process 8983
   identical  app/controllers/admin/application_controller.rb
/Users/dwright/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.5.1/lib/rails/generators/named_base.rb:102:in `block in class_name': undefined method `camelize' for nil:NilClass (NoMethodError)
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.5.1/lib/rails/generators/named_base.rb:102:in `map!'
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.5.1/lib/rails/generators/named_base.rb:102:in `class_name'
	from (erb):3:in `template'
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/2.3.0/erb.rb:864:in `eval'
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/2.3.0/erb.rb:864:in `result'
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/actions/file_manipulation.rb:116:in `block in template'
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:53:in `render'
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:46:in `identical?'
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:72:in `on_conflict_behavior'
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/actions/empty_directory.rb:113:in `invoke_with_conflict_check'
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:60:in `invoke!'
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/actions.rb:94:in `action'
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:25:in `create_file'
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/actions/file_manipulation.rb:115:in `template'
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.5.1/lib/rails/generators/named_base.rb:26:in `block in template'
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.5.1/lib/rails/generators/named_base.rb:60:in `inside_template'
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.5.1/lib/rails/generators/named_base.rb:25:in `template'
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/administrate-0.1.5/lib/generators/administrate/dashboard/dashboard_generator.rb:30:in `create_dashboard_definition'
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.5.1/lib/rails/generators.rb:157:in `invoke'
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/administrate-0.1.5/lib/administrate/generator_helpers.rb:4:in `call_generator'
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/administrate-0.1.5/lib/generators/administrate/install/install_generator.rb:27:in `block in run_dashboard_generators'
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/administrate-0.1.5/lib/generators/administrate/install/install_generator.rb:26:in `each'
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/administrate-0.1.5/lib/generators/administrate/install/install_generator.rb:26:in `run_dashboard_generators'
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.5.1/lib/rails/generators.rb:157:in `invoke'
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.5.1/lib/rails/commands/generate.rb:13:in `<top (required)>'
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:130:in `generate_or_destroy'
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:50:in `generate'
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.5.1/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/dwright/workspace/rails/sample_app/bin/rails:9:in `<top (required)>'
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:268:in `load'
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:268:in `load'
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/dwright/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

**Comment by dannysmith** [comment]
Likewise. I'm getting the same error as @danielyewright.

**Comment by chriscapetown** [comment]
FYI - https://github.com/thoughtbot/administrate/issues/493

**Comment by carlosramireziii** [comment]
@sayshay Does #493 look like the same issue you are experiencing?

**Comment by darrenterhune** [comment]
Stumbled on to this issue today, in a rails app that we want to migrate from home rolled admin to something that speeds dev.

Rails 5.0.1
Ruby 2.3.3

In our case we had this in our `config/routes.rb` file:

```
namespace :admin do
  get '', to: 'dashboard#index'
end
```

Commenting out `get '', to: 'dashboard#index'` and re-running the installer `rails generate administrate:install` works just fine. So in our case it seems that a `dashboards_controller.rb` in the app before the `administrate` install clashes.

**Comment by pablobm** [comment]
It's been a while, so I think this can be closed for now. Please let us know if anyone sees this issue again.
