### ISSUE TITLE
ActiveRecord::AssociationTypeMismatch in Admin::CampingsController#update

### ISSUE THREAD

**Issue by nicolaswecandoit** [thoughtbot/administrate#635]
I have rails app with GEM administrate https://github.com/thoughtbot/administrate

When i try to update information in localhost:3000/admin i have one error  ActiveRecord::AssociationTypeMismatch in Admin::CampingsController#update

```
Region(#40323504) expected, got String(#2839416)

Rails.root: C:/Sites/SiteDeCamping

Application Trace | Framework Trace | Full Trace
activerecord (4.2.5.1) lib/active_record/associations/association.rb:218:in `raise_on_type_mismatch!'
activerecord (4.2.5.1) lib/active_record/associations/belongs_to_association.rb:12:in `replace'
activerecord (4.2.5.1) lib/active_record/associations/singular_association.rb:17:in `writer'
activerecord (4.2.5.1) lib/active_record/associations/builder/association.rb:123:in `region='
activerecord (4.2.5.1) lib/active_record/attribute_assignment.rb:54:in `public_send'
activerecord (4.2.5.1) lib/active_record/attribute_assignment.rb:54:in `_assign_attribute'
activerecord (4.2.5.1) lib/active_record/attribute_assignment.rb:41:in `block in assign_attributes'
actionpack (4.2.5.1) lib/action_controller/metal/strong_parameters.rb:185:in `each_pair'
actionpack (4.2.5.1) lib/action_controller/metal/strong_parameters.rb:185:in `each_pair'
activerecord (4.2.5.1) lib/active_record/attribute_assignment.rb:35:in `assign_attributes'
activerecord (4.2.5.1) lib/active_record/persistence.rb:251:in `block in update'
activerecord (4.2.5.1) lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
activerecord (4.2.5.1) lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
activerecord (4.2.5.1) lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
activerecord (4.2.5.1) lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
activerecord (4.2.5.1) lib/active_record/transactions.rb:220:in `transaction'
activerecord (4.2.5.1) lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
activerecord (4.2.5.1) lib/active_record/persistence.rb:250:in `update'
administrate (0.2.2) app/controllers/administrate/application_controller.rb:53:in `update'
actionpack (4.2.5.1) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (4.2.5.1) lib/abstract_controller/base.rb:198:in `process_action'
actionpack (4.2.5.1) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (4.2.5.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (4.2.5.1) lib/active_support/callbacks.rb:117:in `call'
activesupport (4.2.5.1) lib/active_support/callbacks.rb:117:in `call'
activesupport (4.2.5.1) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
activesupport (4.2.5.1) lib/active_support/callbacks.rb:505:in `call'
activesupport (4.2.5.1) lib/active_support/callbacks.rb:505:in `call'
activesupport (4.2.5.1) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
activesupport (4.2.5.1) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
activesupport (4.2.5.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.5.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (4.2.5.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.2.5.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (4.2.5.1) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (4.2.5.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.5.1) lib/active_support/notifications.rb:164:in `instrument'
actionpack (4.2.5.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.2.5.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
activerecord (4.2.5.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (4.2.5.1) lib/abstract_controller/base.rb:137:in `process'
actionview (4.2.5.1) lib/action_view/rendering.rb:30:in `process'
actionpack (4.2.5.1) lib/action_controller/metal.rb:196:in `dispatch'
actionpack (4.2.5.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.2.5.1) lib/action_controller/metal.rb:237:in `block in action'
actionpack (4.2.5.1) lib/action_dispatch/routing/route_set.rb:74:in `call'
actionpack (4.2.5.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
actionpack (4.2.5.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
actionpack (4.2.5.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
actionpack (4.2.5.1) lib/action_dispatch/journey/router.rb:30:in `each'
actionpack (4.2.5.1) lib/action_dispatch/journey/router.rb:30:in `serve'
actionpack (4.2.5.1) lib/action_dispatch/routing/route_set.rb:815:in `call'
rack (1.6.4) lib/rack/etag.rb:24:in `call'
rack (1.6.4) lib/rack/conditionalget.rb:38:in `call'
rack (1.6.4) lib/rack/head.rb:13:in `call'
actionpack (4.2.5.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.2.5.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.2.5.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
activerecord (4.2.5.1) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.2.5.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
activerecord (4.2.5.1) lib/active_record/migration.rb:377:in `call'
actionpack (4.2.5.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.2.5.1) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
activesupport (4.2.5.1) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
activesupport (4.2.5.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.5.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.2.5.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.2.5.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
actionpack (4.2.5.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
web-console (2.3.0) lib/web_console/middleware.rb:28:in `block in call'
web-console (2.3.0) lib/web_console/middleware.rb:18:in `catch'
web-console (2.3.0) lib/web_console/middleware.rb:18:in `call'
actionpack (4.2.5.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.2.5.1) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.2.5.1) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.2.5.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.2.5.1) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.2.5.1) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.2.5.1) lib/rails/rack/logger.rb:20:in `call'
actionpack (4.2.5.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
rack (1.6.4) lib/rack/runtime.rb:18:in `call'
activesupport (4.2.5.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
rack (1.6.4) lib/rack/lock.rb:17:in `call'
actionpack (4.2.5.1) lib/action_dispatch/middleware/static.rb:116:in `call'
rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
railties (4.2.5.1) lib/rails/engine.rb:518:in `call'
railties (4.2.5.1) lib/rails/application.rb:165:in `call'
rack (1.6.4) lib/rack/lock.rb:17:in `call'
rack (1.6.4) lib/rack/content_length.rb:15:in `call'
rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
```

/admin/campings_controller.rb

```
module Admin
  class Campings
Controller < Admin::ApplicationController
end

end
```

camping.rb
    class Camping < ActiveRecord::Base
      belongs_to :ville
      belongs_to :departement
      belongs_to :region

```
end
```

region.rb

```
class Region < ActiveRecord::Base
  has_many :departements
  has_many :villes
  has_many :campings
end
```

ville.rb

```
class Ville < ActiveRecord::Base
  belongs_to :departement
  has_many :campings
end
```

departement.rb

```
class Departement < ActiveRecord::Base
  belongs_to :region
  has_many :villes
  has_many :campings
end
```

So can you help ? Do u need another copy and paste to answer ?

Thanks for your help :)
Ps: i m french by the way i m sorry for my bad english

**Comment by jakesen** [comment]
It might be helpful to paste your dashboard class too.

**Comment by carlosramireziii** [comment]
@nicolaswecandoit Were you able to work past your issue here? At first glance it looks like maybe you have a field type set for `String` when it should be an association instead. 

As @jakesen mentioned, a Gist of your dashboard, routes, and controller would be helpful for debugging. 

Let us know if this is still an issue or if we can close it up. Thanks!

**Comment by carlosramireziii** [comment]
Closing for now but feel free to re-open if you think it's still an issue. Thanks!
