### ISSUE TITLE
"uninitialized constant AverageCach (NameError)" when trying to generate administrate:install

### ISSUE THREAD

**Issue by etcook** [thoughtbot/administrate#800]
When I try to do a generate administrate:install, i get the following:

```
ecook$ rails generate administrate:install
Running via Spring preloader in process 65794
   identical  app/controllers/admin/application_controller.rb
/Users/ecook/.rvm/gems/ruby-2.4.0/gems/administrate-0.4.0/lib/generators/administrate/dashboard/dashboard_generator.rb:111:in `const_get': uninitialized constant AverageCach (NameError)
        from /Users/ecook/.rvm/gems/ruby-2.4.0/gems/administrate-0.4.0/lib/generators/administrate/dashboard/dashboard_generator.rb:111:in `klass'
        from /Users/ecook/.rvm/gems/ruby-2.4.0/gems/administrate-0.4.0/lib/generators/administrate/dashboard/dashboard_generator.rb:47:in `attributes'
        from (erb):11:in `template'
        from /Users/ecook/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/erb.rb:896:in `eval'
        from /Users/ecook/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/erb.rb:896:in `result'
        from /Users/ecook/.rvm/gems/ruby-2.4.0/gems/thor-0.19.1/lib/thor/actions/file_manipulation.rb:116:in `block in template'
        from /Users/ecook/.rvm/gems/ruby-2.4.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:53:in `render'
        from /Users/ecook/.rvm/gems/ruby-2.4.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:46:in `identical?'
        from /Users/ecook/.rvm/gems/ruby-2.4.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:72:in `on_conflict_behavior'
        from /Users/ecook/.rvm/gems/ruby-2.4.0/gems/thor-0.19.1/lib/thor/actions/empty_directory.rb:113:in `invoke_with_conflict_check'
        from /Users/ecook/.rvm/gems/ruby-2.4.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:60:in `invoke!'
        from /Users/ecook/.rvm/gems/ruby-2.4.0/gems/thor-0.19.1/lib/thor/actions.rb:94:in `action'
        from /Users/ecook/.rvm/gems/ruby-2.4.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:25:in `create_file'
        from /Users/ecook/.rvm/gems/ruby-2.4.0/gems/thor-0.19.1/lib/thor/actions/file_manipulation.rb:115:in `template'
        from /Users/ecook/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/generators/named_base.rb:26:in `block in template'
        from /Users/ecook/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/generators/named_base.rb:64:in `inside_template'
        from /Users/ecook/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/generators/named_base.rb:25:in `template'
        from /Users/ecook/.rvm/gems/ruby-2.4.0/gems/administrate-0.4.0/lib/generators/administrate/dashboard/dashboard_generator.rb:30:in `create_dashboard_definition'
        from /Users/ecook/.rvm/gems/ruby-2.4.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /Users/ecook/.rvm/gems/ruby-2.4.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /Users/ecook/.rvm/gems/ruby-2.4.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
        from /Users/ecook/.rvm/gems/ruby-2.4.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
        from /Users/ecook/.rvm/gems/ruby-2.4.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
        from /Users/ecook/.rvm/gems/ruby-2.4.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
        from /Users/ecook/.rvm/gems/ruby-2.4.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
        from /Users/ecook/.rvm/gems/ruby-2.4.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /Users/ecook/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/generators.rb:180:in `invoke'
        from /Users/ecook/.rvm/gems/ruby-2.4.0/gems/administrate-0.4.0/lib/administrate/generator_helpers.rb:4:in `call_generator'
        from /Users/ecook/.rvm/gems/ruby-2.4.0/gems/administrate-0.4.0/lib/generators/administrate/install/install_generator.rb:27:in `block in run_dashboard_generators'
        from /Users/ecook/.rvm/gems/ruby-2.4.0/gems/administrate-0.4.0/lib/generators/administrate/install/install_generator.rb:26:in `each'
        from /Users/ecook/.rvm/gems/ruby-2.4.0/gems/administrate-0.4.0/lib/generators/administrate/install/install_generator.rb:26:in `run_dashboard_generators'
        from /Users/ecook/.rvm/gems/ruby-2.4.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /Users/ecook/.rvm/gems/ruby-2.4.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /Users/ecook/.rvm/gems/ruby-2.4.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
        from /Users/ecook/.rvm/gems/ruby-2.4.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
        from /Users/ecook/.rvm/gems/ruby-2.4.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
        from /Users/ecook/.rvm/gems/ruby-2.4.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
        from /Users/ecook/.rvm/gems/ruby-2.4.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
        from /Users/ecook/.rvm/gems/ruby-2.4.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /Users/ecook/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/generators.rb:180:in `invoke'
        from /Users/ecook/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/commands/generate.rb:13:in `<top (required)>'
        from /Users/ecook/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:138:in `require_command!'
        from /Users/ecook/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:145:in `generate_or_destroy'
        from /Users/ecook/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:60:in `generate'
        from /Users/ecook/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
        from /Users/ecook/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/commands.rb:18:in `<top (required)>'
        from /Users/ecook/Dropbox/Development/apps/swg/bin/rails:9:in `<top (required)>'
        from /Users/ecook/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/ecook/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from -e:1:in `<main>'
```

**Comment by BenMorganIO** [comment]
Hey, we need more information than this. I have a feeling you may have a model called `AverageCach` somewhere.
