### ISSUE TITLE
spec/generators/dashboard_generator_spec.rb failing randomly?

### ISSUE THREAD

**Issue by pustomytnyk** [thoughtbot/administrate#846]
Check https://circleci.com/gh/ianagne/administrate/37 or https://circleci.com/gh/thoughtbot/administrate/1966

`spec/generators/dashboard_generator_spec.rb:162` seem to fail randomly. Both on CI and locally.

**Comment by pustomytnyk** [comment]
I confirm that sometimes the test generates dashboard with empty attributes list.

**Comment by ianagne** [comment]
Attempted running seed 12167 in bisect mode, but receive the following error:

```
Starting bisect with 1 failing example and 286 non-failing examples.
Checking that failure(s) are order-dependent... failure appears to be order-dependent

Round 1: bisecting over non-failing examples 1-286 .. multiple culprits detected - splitting candidates (14.21 seconds)
Round 2: bisecting over non-failing examples 1-143 .. ignoring examples 73-143 (17.48 seconds)
Round 3: bisecting over non-failing examples 1-72 .. ignoring examples 37-72 (14.8 seconds)
Round 4: bisecting over non-failing examples 1-36 .. ignoring examples 19-36 (14.36 seconds)
Round 5: bisecting over non-failing examples 1-18 .. ignoring examples 10-18 (14.42 seconds)
Round 6: bisecting over non-failing examples 1-9

Bisect failed! Failed to get results from the spec run. Spec run output:

/Users/Igon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-4.2.8/lib/rails/generators/base.rb:17:in `<class:Base>': uninitialized constant Rails::Generators::Actions (NameError)
	from /Users/Igon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-4.2.8/lib/rails/generators/base.rb:15:in `<module:Generators>'
	from /Users/Igon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-4.2.8/lib/rails/generators/base.rb:11:in `<module:Rails>'
	from /Users/Igon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-4.2.8/lib/rails/generators/base.rb:10:in `<top (required)>'
	from /Users/Igon/Projects/administrate/lib/administrate/view_generator.rb:1:in `require'
	from /Users/Igon/Projects/administrate/lib/administrate/view_generator.rb:1:in `<top (required)>'
	from /Users/Igon/Projects/administrate/lib/generators/administrate/views/index_generator.rb:1:in `require'
	from /Users/Igon/Projects/administrate/lib/generators/administrate/views/index_generator.rb:1:in `<top (required)>'
	from /Users/Igon/Projects/administrate/spec/generators/views/index_generator_spec.rb:2:in `require'
	from /Users/Igon/Projects/administrate/spec/generators/views/index_generator_spec.rb:2:in `<top (required)>'
	from /Users/Igon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.1/lib/rspec/core/configuration.rb:1435:in `load'
	from /Users/Igon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.1/lib/rspec/core/configuration.rb:1435:in `block in load_spec_files'
	from /Users/Igon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.1/lib/rspec/core/configuration.rb:1433:in `each'
	from /Users/Igon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.1/lib/rspec/core/configuration.rb:1433:in `load_spec_files'
	from /Users/Igon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.1/lib/rspec/core/runner.rb:100:in `setup'
	from /Users/Igon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.1/lib/rspec/core/runner.rb:86:in `run'
	from /Users/Igon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.1/lib/rspec/core/runner.rb:71:in `run'
	from /Users/Igon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.1/lib/rspec/core/runner.rb:45:in `invoke'
	from /Users/Igon/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rspec-core-3.5.1/exe/rspec:4:in `<main>'
```

**Comment by pustomytnyk** [comment]
It requires at least three examples to be reproduced.
`rspec --seed 12167 --example "searches using lower() + LIKE for all searchable fields" --example "populates default dashboards based on current ActiveRecord models" --example "Administrate::Generators::DashboardGenerator dashboard definition file #attribute_types detects boolean values"`

**Comment by pustomytnyk** [comment]
Obviously smth about redefining User class and `remove_constants :User`.
