### ISSUE TITLE
pagination translation for administrate

### ISSUE THREAD

**Issue by megetron** [thoughtbot/administrate#878]
The project I am working on using administrate and it throws exceptions on missing translations.
Seems like the pagination used by administrate is not translated to he language?

I could translate it but the pagination is external project? or it is an administrate related code? couldn't find the translation that missing  (he.views.pagination.next) anywhere in your code. 
please advice, the error below:

```
Rendered admin/orders/index.html.erb within layouts/admin/application (6941.4ms)
Completed 500 Internal Server Error in 7061ms (ActiveRecord: 76.0ms)


  
ActionView::Template::Error (translation missing: he.views.pagination.next):
     7:     remote:        data-remote
     8: -%>
     9: <span class="next">
    10:   <%= link_to_unless current_page.last?, t('views.pagination.next').html_safe, url, rel: 'next', remote: remote %>
    11: </span>
  
app/views/admin/orders/index.html.erb:60:in `_app_views_admin_orders_index_html_erb__3393215105644009834_70212765289220'
app/controllers/admin/application_controller.rb:27:in `index'

NoMethodError: undefined method `original_exception' for #<ActionView::Template::Error:0x007fb7642ba688>
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/web-console-2.3.0/lib/web_console/extensions.rb:16:in `block in render_exception_with_web_console'
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/web-console-2.3.0/lib/web_console/extensions.rb:3:in `tap'
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/web-console-2.3.0/lib/web_console/extensions.rb:3:in `render_exception_with_web_console'
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.1.0.rc2/lib/action_dispatch/middleware/debug_exceptions.rb:69:in `rescue in call'
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.1.0.rc2/lib/action_dispatch/middleware/debug_exceptions.rb:58:in `call'
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/web-console-2.3.0/lib/web_console/middleware.rb:28:in `block in call'
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/web-console-2.3.0/lib/web_console/middleware.rb:18:in `catch'
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/web-console-2.3.0/lib/web_console/middleware.rb:18:in `call'
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.1.0.rc2/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.1.0.rc2/lib/rails/rack/logger.rb:36:in `call_app'
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.1.0.rc2/lib/rails/rack/logger.rb:24:in `block in call'
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.1.0.rc2/lib/active_support/tagged_logging.rb:69:in `block in tagged'
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.1.0.rc2/lib/active_support/tagged_logging.rb:26:in `tagged'
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.1.0.rc2/lib/active_support/tagged_logging.rb:69:in `tagged'
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.1.0.rc2/lib/rails/rack/logger.rb:24:in `call'
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sprockets-rails-3.2.0/lib/sprockets/rails/quiet_assets.rb:13:in `call'
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.1.0.rc2/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.1.0.rc2/lib/action_dispatch/middleware/request_id.rb:25:in `call'
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.2/lib/rack/method_override.rb:22:in `call'
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.2/lib/rack/runtime.rb:22:in `call'
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.1.0.rc2/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.1.0.rc2/lib/action_dispatch/middleware/executor.rb:12:in `call'
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.1.0.rc2/lib/action_dispatch/middleware/static.rb:125:in `call'
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.2/lib/rack/sendfile.rb:111:in `call'
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.1.0.rc2/lib/rails/engine.rb:522:in `call'
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.8.2/lib/puma/configuration.rb:224:in `call'
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.8.2/lib/puma/server.rb:600:in `handle_request'
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.8.2/lib/puma/server.rb:435:in `process_client'
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.8.2/lib/puma/server.rb:299:in `block in run'
	from /Users/guy/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.8.2/lib/puma/thread_pool.rb:120:in `block in spawn_thread'

```

**Comment by nickcharlton** [comment]
Hi! The pagination support is handled by Kaminari, you can see the docs for it here: https://github.com/kaminari/kaminari#i18n-and-labels

I'm not really sure what Kaminari's approach to translations is, but I'd have a look and perhaps try and contribute something there?

**Comment by 6temes** [comment]
You may want to check this:

https://www.localeapp.com/projects/1985

**Comment by megetron** [comment]
Thank you guy. 
seems like the language :he  missing I can add it or fallback missing translations to default :en translation.
