### ISSUE TITLE
Is it possible to use administrate inside of an rails engine?

### ISSUE THREAD

**Issue by blaszczakphoto** [thoughtbot/administrate#897]
I was trying to extract admin of my rails app to separate engine. But I found impossible to use administrate CLI generators inside of my engine. Is there any workaround this?

```
rg administrate:dashboard SocialIcon
/home/mariusz/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/administrate-0.7.0/lib/generators/administrate/dashboard/dashboard_generator.rb:32:in `create_dashboard_definition': undefined method `join' for nil:NilClass (NoMethodError)
	from /home/mariusz/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /home/mariusz/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/mariusz/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /home/mariusz/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `each'
	from /home/mariusz/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `map'
	from /home/mariusz/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `invoke_all'
	from /home/mariusz/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/group.rb:232:in `dispatch'
	from /home/mariusz/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /home/mariusz/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/generators.rb:180:in `invoke'
	from /home/mariusz/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/commands/generate.rb:13:in `<top (required)>'
	from /home/mariusz/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/engine/commands_tasks.rb:68:in `require'
	from /home/mariusz/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/engine/commands_tasks.rb:68:in `require_command!'
	from /home/mariusz/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/engine/commands_tasks.rb:73:in `generate_or_destroy'
	from /home/mariusz/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/engine/commands_tasks.rb:44:in `generate'
	from /home/mariusz/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/engine/commands_tasks.rb:37:in `run_command!'
	from /home/mariusz/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/engine/commands.rb:14:in `<top (required)>'
	from bin/rails:13:in `require'
	from bin/rails:13:in `<main>'
```

**Comment by nickcharlton** [comment]
Administrate already is a Rails Engine, but I don't know of a reason why it shouldn't be possible to nest it.

The line where you're getting that error is:

```ruby
Rails.root.join("app/dashboards/#{file_name}_dashboard.rb"),
```

My suspicion was that `Rails.root` is nil, and [this SO thread][] backs that up. To allow this to work, I think we'd need to be a bit smarter about figuring out what `Rails.root` should really be.

Do you think you'd be able to take a crack at that?

[this SO thread]: http://stackoverflow.com/questions/11615635/rails-root-from-engine

**Comment by vbrazo** [comment]
I can't run the generator inside a rails engine either

```ruby
(base) VMBP:accounts voliveira$ rails generate administrate:install 
Traceback (most recent call last):
	24: from bin/rails:24:in `<main>'
	23: from bin/rails:24:in `require'
	22: from /Users/voliveira/.rvm/gems/ruby-2.5.1/gems/railties-5.2.3/lib/rails/engine/commands.rb:9:in `<top (required)>'
	21: from /Users/voliveira/.rvm/gems/ruby-2.5.1/gems/railties-5.2.3/lib/rails/engine/commands.rb:9:in `require'
	20: from /Users/voliveira/.rvm/gems/ruby-2.5.1/gems/railties-5.2.3/lib/rails/commands.rb:18:in `<top (required)>'
	19: from /Users/voliveira/.rvm/gems/ruby-2.5.1/gems/railties-5.2.3/lib/rails/command.rb:46:in `invoke'
	18: from /Users/voliveira/.rvm/gems/ruby-2.5.1/gems/railties-5.2.3/lib/rails/command/base.rb:65:in `perform'
	17: from /Users/voliveira/.rvm/gems/ruby-2.5.1/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	16: from /Users/voliveira/.rvm/gems/ruby-2.5.1/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	15: from /Users/voliveira/.rvm/gems/ruby-2.5.1/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	14: from /Users/voliveira/.rvm/gems/ruby-2.5.1/gems/railties-5.2.3/lib/rails/commands/generate/generate_command.rb:26:in `perform'
	13: from /Users/voliveira/.rvm/gems/ruby-2.5.1/gems/railties-5.2.3/lib/rails/generators.rb:276:in `invoke'
	12: from /Users/voliveira/.rvm/gems/ruby-2.5.1/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	11: from /Users/voliveira/.rvm/gems/ruby-2.5.1/gems/thor-0.20.3/lib/thor/group.rb:232:in `dispatch'
	10: from /Users/voliveira/.rvm/gems/ruby-2.5.1/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `invoke_all'
	 9: from /Users/voliveira/.rvm/gems/ruby-2.5.1/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `map'
	 8: from /Users/voliveira/.rvm/gems/ruby-2.5.1/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `each'
	 7: from /Users/voliveira/.rvm/gems/ruby-2.5.1/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `block in invoke_all'
	 6: from /Users/voliveira/.rvm/gems/ruby-2.5.1/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	 5: from /Users/voliveira/.rvm/gems/ruby-2.5.1/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	 4: from /Users/voliveira/.rvm/gems/ruby-2.5.1/gems/administrate-0.11.0/lib/generators/administrate/install/install_generator.rb:14:in `run_routes_generator'
	 3: from /Users/voliveira/.rvm/gems/ruby-2.5.1/gems/administrate-0.11.0/lib/generators/administrate/install/install_generator.rb:45:in `dashboard_resources'
	 2: from /Users/voliveira/.rvm/gems/ruby-2.5.1/gems/administrate-0.11.0/lib/administrate/namespace.rb:8:in `resources'
	 1: from /Users/voliveira/.rvm/gems/ruby-2.5.1/gems/administrate-0.11.0/lib/administrate/namespace.rb:14:in `routes'
/Users/voliveira/.rvm/gems/ruby-2.5.1/gems/administrate-0.11.0/lib/administrate/namespace.rb:26:in `all_routes': undefined method `routes' for nil:NilClass (NoMethodError)
```

**Comment by nickcharlton** [comment]
I'm going to close this as the last discussion was a while ago and this use case seems to be unusual.

**Comment by mehdi-farsi** [comment]
It works just fine but if you don't want to use `isolate_namespace` you must replace `YourEngine::Engine.routes.draw` by `Rails.application.routes.draw` and you should be able to make it work with the `dummy` app.
