### ISSUE TITLE
convert lives to life

### ISSUE THREAD

**Issue by tooooolong** [thoughtbot/administrate#908]
Model name is `Live`, table name is `lives`
when generate dashboard raise
`const_get': uninitialized constant Life (NameError)

**Comment by tooooolong** [comment]
```
/Users/changhong/.rvm/gems/ruby-2.3.1@mklive/bundler/gems/administrate-a34ee154d9b7/lib/generators/administrate/dashboard/dashboard_generator.rb:111:in `const_get': uninitialized constant Life (NameError)
        from /Users/changhong/.rvm/gems/ruby-2.3.1@mklive/bundler/gems/administrate-a34ee154d9b7/lib/generators/administrate/dashboard/dashboard_generator.rb:111:in `klass'
        from /Users/changhong/.rvm/gems/ruby-2.3.1@mklive/bundler/gems/administrate-a34ee154d9b7/lib/generators/administrate/dashboard/dashboard_generator.rb:47:in `attributes'
        from (erb):11:in `template'
        from /Users/changhong/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/erb.rb:864:in `eval'
        from /Users/changhong/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/erb.rb:864:in `result'
```

**Comment by krzysiek1507** [comment]
Hi, @tooooolong. Model name should be a noun and `Live` is not a noun, so it could be a problem with Rails Inflector. You should consider changing model's name.

**Comment by tooooolong** [comment]
OK，thank you very much
