### ISSUE TITLE
Error while run: rails generate administrate:install on existing project 

### ISSUE THREAD

**Issue by chavdareto** [thoughtbot/administrate#985]
Me and my team are trying to integrate **administrate** in our project. 
While we try to install it we encounter a lot of problems. 
ruby version: **2.3.1**
rails version: **4.2.9**

```
rails generate administrate:install

   identical  app/controllers/admin/application_controller.rb
   identical  app/dashboards/master_card_dashboard.rb
   identical  app/controllers/admin/master_cards_controller.rb
   identical  app/dashboards/card_template_dashboard.rb
   identical  app/controllers/admin/card_templates_controller.rb
   identical  app/dashboards/preauth_dashboard.rb
   identical  app/controllers/admin/preauths_controller.rb
   identical  app/dashboards/transaction_dashboard.rb
   identical  app/controllers/admin/transactions_controller.rb
   identical  app/dashboards/master_card_fee_transaction_dashboard.rb
   identical  app/controllers/admin/master_card_fee_transactions_controller.rb
   identical  app/dashboards/one_time_password_dashboard.rb
   identical  app/controllers/admin/one_time_passwords_controller.rb
   identical  app/dashboards/account_dashboard.rb
   identical  app/controllers/admin/accounts_controller.rb
   identical  app/dashboards/legal_document_dashboard.rb
   identical  app/controllers/admin/legal_documents_controller.rb
/Users/chavdardimitrov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/administrate-0.8.1/lib/generators/administrate/dashboard/dashboard_generator.rb:111:in `const_get': uninitialized constant PersonalDatum (NameError)
	from /Users/chavdardimitrov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/administrate-0.8.1/lib/generators/administrate/dashboard/dashboard_generator.rb:111:in `klass'
	from /Users/chavdardimitrov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/administrate-0.8.1/lib/generators/administrate/dashboard/dashboard_generator.rb:47:in `attributes'
	from (erb):11:in `template'
	from /Users/chavdardimitrov/.rbenv/versions/2.3.1/lib/ruby/2.3.0/erb.rb:864:in `eval'
	from /Users/chavdardimitrov/.rbenv/versions/2.3.1/lib/ruby/2.3.0/erb.rb:864:in `result'
	from /Users/chavdardimitrov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/actions/file_manipulation.rb:116:in `block in template'
	from /Users/chavdardimitrov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/actions/create_file.rb:53:in `render'
	from /Users/chavdardimitrov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/actions/create_file.rb:46:in `identical?'
	from /Users/chavdardimitrov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/actions/create_file.rb:72:in `on_conflict_behavior'
	from /Users/chavdardimitrov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/actions/empty_directory.rb:113:in `invoke_with_conflict_check'
	from /Users/chavdardimitrov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/actions/create_file.rb:60:in `invoke!'
	from /Users/chavdardimitrov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/actions.rb:95:in `action'
	from /Users/chavdardimitrov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/actions/create_file.rb:25:in `create_file'
	from /Users/chavdardimitrov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/actions/file_manipulation.rb:115:in `template'
	from /Users/chavdardimitrov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.9/lib/rails/generators/named_base.rb:26:in `block in template'
	from /Users/chavdardimitrov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.9/lib/rails/generators/named_base.rb:60:in `inside_template'
	from /Users/chavdardimitrov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.9/lib/rails/generators/named_base.rb:25:in `template'
	from /Users/chavdardimitrov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/administrate-0.8.1/lib/generators/administrate/dashboard/dashboard_generator.rb:30:in `create_dashboard_definition'
	from /Users/chavdardimitrov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/chavdardimitrov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/chavdardimitrov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /Users/chavdardimitrov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `each'
	from /Users/chavdardimitrov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `map'
	from /Users/chavdardimitrov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `invoke_all'
	from /Users/chavdardimitrov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/group.rb:232:in `dispatch'
	from /Users/chavdardimitrov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Users/chavdardimitrov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.9/lib/rails/generators.rb:157:in `invoke'
	from /Users/chavdardimitrov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/administrate-0.8.1/lib/administrate/generator_helpers.rb:4:in `call_generator'
	from /Users/chavdardimitrov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/administrate-0.8.1/lib/generators/administrate/install/install_generator.rb:27:in `block in run_dashboard_generators'
	from /Users/chavdardimitrov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/administrate-0.8.1/lib/generators/administrate/install/install_generator.rb:26:in `each'
	from /Users/chavdardimitrov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/administrate-0.8.1/lib/generators/administrate/install/install_generator.rb:26:in `run_dashboard_generators'
	from /Users/chavdardimitrov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/chavdardimitrov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/chavdardimitrov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /Users/chavdardimitrov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `each'
	from /Users/chavdardimitrov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `map'
	from /Users/chavdardimitrov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `invoke_all'
	from /Users/chavdardimitrov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/group.rb:232:in `dispatch'
	from /Users/chavdardimitrov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Users/chavdardimitrov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.9/lib/rails/generators.rb:157:in `invoke'
	from /Users/chavdardimitrov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.9/lib/rails/commands/generate.rb:13:in `<top (required)>'
	from /Users/chavdardimitrov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.9/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
	from /Users/chavdardimitrov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.9/lib/rails/commands/commands_tasks.rb:130:in `generate_or_destroy'
	from /Users/chavdardimitrov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.9/lib/rails/commands/commands_tasks.rb:50:in `generate'
	from /Users/chavdardimitrov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.9/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/chavdardimitrov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.9/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by nickcharlton** [comment]
Hi!

For some of those, it looks like the generator has already been run. It's a generator, so this is probably fine.

For `const_get': uninitialized constant PersonalDatum (NameError)`, it sounds like the generator isn't able to load `PersonalDatum`.

* Is this a model?
* Are you using any namespaced controllers?
* Is this working normally with other Rails controllers?

**Comment by chavdareto** [comment]
1. For PersonalDatum is it a model ? 
I can't find such a thing anywhere in the project defined, probably later i will be able to give you more information on this.

2. Yes we are using namespaced controllers, and namespaced models

3. No, we have not yet tuned it, we try to solve these problems during installation.

**Comment by nickcharlton** [comment]
Hi @chavdareto! How are you getting on with this?

I'm not quite sure where y`PersonalDatum` would otherwise come from, so it being a model or similar would be my first guess.

**Comment by chavdareto** [comment]
Hello @nickcharlton 
We couldn't resolve the issue and dropped the idea of using the administrate gem for our current project at the moment. Thanks for the support anyway.
